(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"cuento_macabro_atlas_1", frames: [[444,1637,113,199],[0,1637,442,116],[0,0,962,657],[0,1046,962,329],[0,659,962,385],[0,1377,962,258],[0,1755,197,48]]},
		{name:"cuento_macabro_atlas_2", frames: [[0,0,1324,1008],[0,1010,1310,992]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_17 = function() {
	this.initialize(img.CachedBmp_17);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2718,1226);


(lib.CachedBmp_16 = function() {
	this.initialize(ss["cuento_macabro_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_15 = function() {
	this.initialize(ss["cuento_macabro_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_10 = function() {
	this.initialize(ss["cuento_macabro_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_8 = function() {
	this.initialize(ss["cuento_macabro_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_9 = function() {
	this.initialize(ss["cuento_macabro_atlas_2"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_6 = function() {
	this.initialize(ss["cuento_macabro_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_4 = function() {
	this.initialize(ss["cuento_macabro_atlas_1"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_5 = function() {
	this.initialize(ss["cuento_macabro_atlas_2"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_18 = function() {
	this.initialize(ss["cuento_macabro_atlas_1"]);
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Símbolo4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#435058").s().p("AjaDbQhbhaAAiBQAAiABbhaQBahbCAAAQCBAABaBbQBbBaAACAQAACBhbBaQhaBbiBAAQiAAAhahbg");
	this.shape.setTransform(31,31);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,62,62);


(lib.Símbolo3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A3A151").s().p("AheEuQglgJgPgKIgWgTQgOgMgLgCQgIgCgTABIgGABIgEABIgEgBQgIAAgFgCIAIgCQgDgFABgHQACgNARgPQAVgSASgDIAfAAQAFABACABQAEACABAFQACAKgBAJIACAFQAFAPAJALQAKALAQAKIAeAPQAMAGAGAHQAHALgGAJgAEdBSIgGgCQgNgGgMAAIgHgBQgEgCgBgDQAAgDAFACIAIABQAUABASAEQALADAHAAQAAAAABAAQAAABAAAAQAAABAAAAQAAABgBABIgFACIgOABgAA7hYIgFgBIgKgGIgPgJIgHgLIgIgJQgHgIgBgIIgBgOIgBgGQgBgEAAgGIAAgKIABgHIADgEQABgGAGgHQAjgzAgggQAJgJAHgBQAKgBAFAIIABADIgDABIgBAAIAFABIADACIAHAIIADADQAGACAAACQgCACgEABQgCABgGABQgLADgHAGIgCACIAAABIgGAGQgDAFgEAAIgDACQgHAJgLAUIAAAAIgQAkIAGAFIADADIABgBQAJgMARgGQALgEAVgEIAggFQAHgCAFACQAGACABAEIgDAEQgHAFgTADQgSAEgHAGQgDADAAACQgBAFAFAAIAEgCQAIgGAOgCIAUgEIAAABQgFAEgKADIgPAFQgKAEgTAUIgBABIAHABQAKABAeABQAKAAADACQAGAEAAAHQAAAFgCAFIgHgDIgKgGQgPgEgHAHIgGAJIgKAKIgSAAIgBABQgNAHgQAAIgBAAIgBABIgBgBgABDhgIAIgBIgGAAgABdkSIgGAKIgBACIgOAPQgNAJgFAGQgEAFAAAGQgBAGADAFQAEgLAEgGIAOgMIAGgHIAAACQAFgDAGgKIABgBIABgBQAJgKAKgDQgDADgIAGQgKAIgJALIAMgLIAAgBIAFgFIAGgEIAHgDIAEgCIAAgBIAEABIgDgFIgDgCIgBgDIgBABIABgBIAAgBIgMgBIgIAIgAiahjIgDABIACgQIABgKIAAgFQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAQAKQADADADAIQgCAEgEgDIgGgEQgCgCgDgBIAEAHQACAFgDADQgCADgDABQgEAAgCgDgAg9iXQgBAAgBAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQABgDAEgBIAGgIIAJgLQAEgIABgLQACgKAAgKIgRgoQgHgQgHgGQgLgIgcADQgbADgOAHQgMAIgPASIgOASIABADIAAAOIgCAEIgCADIgFABIgCgBQgXAVgwAFQgSAAgIAFIgHADQgFABgBgEIgBAAQAJgRAXgNIALgIIgKAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAIAXgEIAFgCQAYgRATgUIARgWQAOgPASgNQAFgDAEgBIAJAAIAdAAQAgAAANAJQALAIAHAPQAQAdABAgQAKAaADAPIAEAKIABABIAAACQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDAAQgPALgVAAIgIAAg");
	this.shape.setTransform(49.0818,31.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A3A151").s().p("Ah8E8IABgDIACABIgDADgAiWEvIACAAIgBAAgAidEpQgDgCgFgCIgEgCIgKgDQgXgNgKgLIgRgWQgLgPgKgEQgIgEgSgDIgGAAIgFgBQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQgIgBgEgDIAIgBQgCgFADgHQAFgNATgJQAYgNATABIAdAGIAIAEQADADgBAGQABAJgDAJIABAEQABARAGAMQAHANAOANIAVASIAUgKQAUgIAXADIAEABQABAAAAABQABAAAAABQAAAAAAABQAAAAgBABQAAABAAAAQAAABAAABQgBAAAAAAQgBABAAAAIgJACQgSAAgQAKIgIADIgCACIACACIgFABIgOAEQgHADgFAAIgCAAgAEPBJQAAgBgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIgkgBIgFgFQAHgHAKABIgEgEQAAgBABAAQAAAAAAgBQABAAAAAAQABAAABAAIADADQAKAKASgEQAHgBABAEQAFgBADgEIAEgKIAEAAQADAFgCAFIgFAIQgGAHgDAAIgHgBIgHACIgDgBgAAognQgEgCgCgDQgHAFgIgDQACgCgCgFQAAgGAKgDIAHgCQAEgBADgCQgEgDgDgEQAEgFAFABIgEgMIgGgKQgGgJACgHIACgPIAAgHQgBgDACgGIACgJIADgHIADgCQAEgHAHgGQAtgpAmgYQALgHAHAAQAKACADAIIABAAQgIgBgHABQgGADgFAHQgEACgEAEIgJALIgHAGQgEADgBAEIgBADIACACIgCAMIAAAAIgDAEIgKAPIALAGQAHAGASAJIAPAAIAgACQAIAAAFAEQAHADgCAHQAAACgGAFQgEADgBADQgGADgKABIgQACQgLABgWAPIgBABIAGACQAJAEAeAHQAJACADAEQAEAEgBAIQgBAHgFAEQgFAGgJABQgGAAgKgDIgqgKIgBABIgHABIAFAFIAFADIAEABQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQgEAEgGgDQgFgGgEAAQAAAGgDAGIgEgKIgBACQgCACgFgCIgIgDIgEgBIgFADQgGAEgMgFQgBAZgTATgAAzgxIAAADIADAAIAFAAIABAAIACgDIgJgBgABQiIIAEAFIABgGIAIgLIgBgDIgMAPgABeiaIABAAIgBAAgAghiMQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQACgCAEAAQACgDAGgEIALgJQAGgGADgLIAFgSIgGgrQgEgTgGgHQgIgKgcgCQgbgDgPADQgOAEgSAQIgRAOIgBADIgDANIgCAEIgDACIgFAAIgCgBQgaAPgxgHQgSgDgJADIgHABQgFAAAAgDIgBgCQANgNAZgIIAggLQAagKAYgRIAWgRQARgLAVgJQAFgDADAAIAJACIAdAGQAfAHALANQAHAKAEAQQAJAhgGAgQAFAbgBAPIACAJIAAABIAAADIgCADQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQgKAFgLAAQgLAAgNgFgACBjMIAAABIgBAAIgBABIACgCg");
	this.shape_1.setTransform(49.5068,32.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#A3A151").s().p("Ah8E8IABgDIACABIgDADgAiWEvIACAAIgBAAgAidEpQgDgCgFgCIgEgCIgKgDQgXgNgKgLIgRgWQgLgPgKgEQgIgEgSgDIgGAAIgFgBQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQgIgBgEgDIAIgBQgCgFADgHQAFgNATgJQAYgNATABIAdAGIAIAEQADADgBAGQABAJgDAJIABAEQABANAEAKIAAgBIAFAAIAHADQADAFgCACIAMADQgHAEgGAAIAAAEIACACIgCAAQACAKAIAIIAFAFIAGAAIAEgBIAHAGIAUgKQAUgIAXADIAEABQABAAAAABQABAAAAABQAAAAAAABQAAAAgBABQAAABAAAAQAAABAAABQgBAAAAAAQgBABAAAAIgJACQgRAAgQAJIACACIgFAAIgGACIgCACIACACIgFABIgOAEQgHADgFAAIgCAAgAinEOIACAAIgEgDgAiyEFIAAADQABABAAABQAAAAABAAQAAABAAAAQABAAAAAAIgBgCIgBgCIAAgCIAAgKIgBAAgAi4D3IgGABQgEADACAHQABADAGADQgBgHACgHIABgDIgBAAIAAAAgAEPBJQAAgBgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIgkgBIgFgFQAHgHAKABIgEgEQAAgBABAAQAAAAAAgBQABAAAAAAQABAAABAAIADADQAKAKASgEQAHgBABAEQAFgBADgEIAEgKIAEAAQADAFgCAFIgFAIQgGAHgDAAIgHgBIgHACIgDgBgAAognQgEgCgCgDQgHAFgIgDQACgCgCgFQAAgGAKgDIAHgCQAEgBADgCQgEgDgDgEQAEgFAFABIgEgMIgGgKQgGgJACgHIACgPIAAgHQgBgDACgGIACgJIADgHIADgCQAEgHAHgGIAIgHIgOgBQgGACgFAHQgDADgCgBQgCgBADgEIAEgGIAGgGQADgBAJAAIAPABIAEgEQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAABIACAAQALAAAIgBIAIgGIAPgLIAJgJIABAAIABgBIADgFIAFgHIACgGQACgFACgCIACgEQAGgCAEAAQAIACADAEQAFACABADQgBAEgDABIgGAAQgFABgEADQgEADgEAIIgbArIgKAJIgGAEIAJAFQAHAGASAJIAPAAIAKABIAFACIAMAAIgDABQgEABgCgBQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQACACAFAAQAGAAAMgEQgGAFgFAIQgGgBgIAGIgNAKIgMAEQgFAEgCADIgJAGIgBABIAGACQAJAEAeAHQAJACADAEQAEAEgBAIQgBAHgFAEQgFAGgJABQgGAAgKgDIgqgKIgBABIgHABIAFAFIAFADIAEABQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQgEAEgGgDQgFgGgEAAQAAAGgDAGIgEgKIgBACQgCACgFgCIgIgDIgEgBIgFADQgGAEgMgFQgBAZgTATgAAzgxIAAADIADAAIAFAAIABAAIACgDIgJgBgABQiIIAEAFIABgGIAIgLIgBgDIgMAPgABeiaIABAAIgBAAgABtivIgEAGIAEgFIABgCIgBABgAByjGIABgBIADgEIgEAFgAghiMQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQACgCAEAAQACgDAGgEIALgJQAGgGADgLIAFgSIgGgrQgEgTgGgHQgCgDgEgCIgEgGQgFgIgPgDIgTgFIgTgBIgIABQgDAAgFAEQgMAGgIAJIgLAOIgGAGIgDAHIgDADIgBADIgDANIgCAEIgDACIgFAAIgCgBQgaAPgxgHQgSgDgJADIgHABQgFAAAAgDIgBgCQANgNAZgIIAggLQAagKAYgRIAWgRQARgLAVgJQAFgDADAAIAJACIAdAGQAfAHALANQAHAKAEAQQAJAhgGAgQAFAbgBAPIACAJIAAABIAAADIgCADQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQgKAFgLAAQgLAAgNgFgABRjGIgDAEIAAAAIgCAAIAFgEgAh0kHIAAABIgBABgAhokSIABgBIAAABIAAAAIgCABgAhMkWIABAAIABAAIgCAAgAgukYIABAAIAAABg");
	this.shape_2.setTransform(49.5068,32.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},7).to({state:[{t:this.shape_2}]},7).wait(7));

	// Capa_1
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#A3A151").s().p("AA1D+QgpgIgcgSIAAAAQgOACgcgBIhfgCQgPAAgIgCQgKgCgTgJIg+gfQgXgLgKgHQgNgKgXgcIgwg9QgMgOgDgHQgGgNgBgfIABgRIgBgBIgBgPIgEgPQgCgJABgFQAFgJAAgFQgBgKABgFQAAgEAEgFIABgDIAFgPQAHgUAZgXIATgPQAYgYARgNQAPgLAOgFIANgDQAQgLAMgCIABAAIATAAQARgGAWgDQArgFBWABIBFAAQArABASAFQAiAHASAXIAIALQAFAHAFADIAOAHQAJAGABAGQABAEgDAEIgCACIgBAOQgFAlgaAdQgJAKgRAMQAPgBAVAAIDcAEQAWAAALAGQAHAFACAJQACAKgGAFQgqADgoASQgZAKgVAQIACAAIABABQALgBAMABQASACAIAEIADACQANAEAIAHIADABQAEACADADIAAAAIAAABIABACQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAEAHgFADIgHACQgWABgSgEIABACQgiAEgigHQgHgBgDgCIgDgBIgGAEQgKAEgPgBQgdAWggARIADAEQAGAGATAeIARAYIARAFQAUAGAxAHQAtAGAYAIQAOAFAFAGQAKAKgEAKQgCAFgFAEIgJgBIgBAGIgHABQgdAGgdADQgrAFg/ACIgFgCQgagMgVgBQAMAJANAHIgBAAIgeABQgtAAgcgFgAFpAyIgGAEIAIAAIgBgEgAhHiMIACAAIgHgBIAFABgAlriWIgGAIIANgMIAAgDIgHAHgAi9joIACgCIgGAAIAEACgAi+jxIgDABIAKACIADgEIgKABg");
	this.shape_3.setTransform(41.3725,34.5408);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#644459").s().p("AF7D6QgegPgQgEQgZgGgmAJQg1ANgKABQgfADg2gOQg9gQgZgBIgMAAQgsAYg5AFQgVACgrgBIg+gBIgQgXQgUgfgFgGIgEgDQAhgSAcgWQAQABAKgEIAGgDIADAAQADADAHABQAiAHAigEIgBgDQASAFAWgBIAGgCQAFgEgDgHQAAAAAAAAQAAgBABAAQAAgBAAAAQgBgBAAgBIAAgBIAAgBIgBAAQgCgDgFgCIgCgBQgJgHgMgFIgDgCQgIgEgSgCQgNgBgKABIgCAAIgBAAQAVgQAZgMQAngSAqgCQAGgGgDgJQgCgJgHgFQgJgHgWAAIjcgDQgWgBgOACQAQgMAKgKQAagcAFglQBIgJAigBIAYgBIB4hUIAcgTQAXgOAOgHIAggNQAUgHAMgGIAngUQAXgKASAFQAhAIAPAuIAGASIACAGIAZAkIABABQATAdAJATIADAAQAKAMAEAKQAEANAAAZQgBAbADALQAEALALANQACAHADADQAFAFAIADIAPALQApAfAJAWQAGAOgBAZQgBAhgOA1QgDAMgEAEQgFAFgLABIgMAAQgXAAgVgIgAEpilIAGAQQgBgIgFgJIAAABgAghCJIAAgBIACAEIgIABIAGgEgAnYg2IAHAAIgCABIgFgBg");
	this.shape_4.setTransform(80.9321,25.8517);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#A39F94").s().p("Aj3E+QhHgCgngIQg6gLgxgeQgNgIgMgJQAVABAaAMIAFACQA/gCArgEQAdgEAdgFIAHgCIABgFIAJAAQAuADApgDQASAAAKgDQAHgDAKgGIARgJQAQgFAhABQAOACAFAFQAEAFgBAJIgCAPIACAlQABAVgMAJQgGAEgTAAgACwgfQgHgCgFgFQgEgDgCgIIgCgFIgCgIIgBABQgCgDAAgFIgBgCIABgBIAAgFIgDABQgCgEAFgDIAAgEQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAgBIABADIAAgBQAcgNAYgSIAUgOIAUgMIAWgKQAOgGAIgEIASgOQALgJAGgDIATgJQAMgFAGgEIAIgGQAEgEAEAAIAJgCIAfABIARABIAJABQALACANAIQAPAGADAIQADAGgCAIQgCAGgFAEQgJAIgQACIgbADIgcAJIgYAHQgHAEgKAGIgTAMQg7AjgbAWIgYARQgIAGgIADQgEACgLACIgPACIgKgCgAB8irIgDAAQgJgUgUgcIABAAIAKABIAAAAIAJgEQALgDATgMIBVg0IATgMIAOgKIAQgGQAUgGAFAAQAJgBARABIAFABQADABAAAHIAAAaQAAAHgCADQgCAFgKAGIgyAaIgUANIgSANIgLAJIgJAGIgKADIgHADIgDABIgBgCQgCACgEACIgHABIgFADIgMADIgLAEIgBAAIgFABIgCABIgEAAQgGABgCABIAMgBIAAABIAJADIAAAAQgHADgKAAIgCAAIgJgBgACPixIAAAAIAAAAg");
	this.shape_5.setTransform(103.5694,33.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]}).wait(21));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,152.6,66.2);


(lib.Interpolación3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.CachedBmp_17();
	this.instance.setTransform(-538.85,-243.05,0.3965,0.3965);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-538.8,-243,1077.6999999999998,486.1);


(lib.Interpolación2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.CachedBmp_16();
	this.instance.setTransform(-28.15,-49.6,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.1,-49.6,56.5,99.5);


(lib.Interpolación1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.CachedBmp_15();
	this.instance.setTransform(-110.4,-28.9,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-110.4,-28.9,221,58);


(lib.boton3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAmBuIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIABgBIgBAAIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgCIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgDIAAgBIAAgDIAAgBIAAgCIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgCIAAgCIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIAAgCIidgCIgNAAIgGAAIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIgBgBIADgBQAHgCAGABIADAAICeABIAAgCIAAgEIAAgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIABAAIgBgEIABgCIgBgGQADgEAFAGQAoA1AxAsIAAABQAFADAAADIgCADIgCADIAAABIgSAWIgiAiIgHAJQgNANgIAKQgJAMgEADIgBABg");
	this.shape.setTransform(28.5773,29.2988);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#435058").s().p("AjODOQhVhVgBh5QABh4BVhWQBWhVB4gBQB5ABBVBVQBXBWAAB4QAAB5hXBVQhVBXh5AAQh4AAhWhXgAiOgsIgEABIABABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAACIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAAAIAAABIAAACIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAACIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAHAAIAMAAICdABIAAACIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAACIAAACIAAABIAAABIAAABIAAAAIAAABIAAABIAAACIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAAAIAAABIAAABIAAABIAAABIAAACIAAABIAAAAIAAABIAAABIAAABIAAACIAAABIAAABIAAABIAAABIAAABIAAABIAAAAIABAAIgBABIAAABIAAABIAAABIAAABIAAABIAAABIAEABIACgCQADgCAKgMQAIgLAMgNIAHgJIAigiIASgWIABgBIABgDIACgDQAAgDgEgDIAAAAQgygtgog0QgFgHgDAEIABAGIgBACIABAFIgBAAIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAADIiegCIgDAAIgDAAIgJABg");
	this.shape_1.setTransform(29.25,29.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,58.5,58.5);


(lib.boton2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAmBuIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIABgBIgBAAIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgCIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgDIAAgBIAAgDIAAgBIAAgCIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgCIAAgCIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIAAgCIidgCIgNAAIgGAAIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIgBgBIADgBQAHgCAGABIADAAICeABIAAgCIAAgEIAAgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIABAAIgBgEIABgCIgBgGQADgEAFAGQAoA1AxAsIAAABQAFADAAADIgCADIgCADIAAABIgSAWIgiAiIgHAJQgNANgIAKQgJAMgEADIgBABg");
	this.shape.setTransform(28.5773,29.2988);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#435058").s().p("AjODOQhVhVgBh5QABh4BVhWQBWhVB4gBQB5ABBVBVQBXBWAAB4QAAB5hXBVQhVBXh5AAQh4AAhWhXgAiOgsIgEABIABABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAACIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAAAIAAABIAAACIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAACIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAHAAIAMAAICdABIAAACIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAACIAAACIAAABIAAABIAAABIAAAAIAAABIAAABIAAACIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAAAIAAABIAAABIAAABIAAABIAAACIAAABIAAAAIAAABIAAABIAAABIAAACIAAABIAAABIAAABIAAABIAAABIAAABIAAAAIABAAIgBABIAAABIAAABIAAABIAAABIAAABIAAABIAEABIACgCQADgCAKgMQAIgLAMgNIAHgJIAigiIASgWIABgBIABgDIACgDQAAgDgEgDIAAAAQgygtgog0QgFgHgDAEIABAGIgBACIABAFIgBAAIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAADIiegCIgDAAIgDAAIgJABg");
	this.shape_1.setTransform(29.25,29.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,58.5,58.5);


(lib.boton1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAmBuIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIABgBIgBAAIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgCIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgDIAAgBIAAgDIAAgBIAAgCIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgCIAAgCIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIAAgCIidgCIgNAAIgGAAIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIgBgBIADgBQAHgCAGABIADAAICeABIAAgCIAAgEIAAgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIABAAIgBgEIABgCIgBgGQADgEAFAGQAoA1AxAsIAAABQAFADAAADIgCADIgCADIAAABIgSAWIgiAiIgHAJQgNANgIAKQgJAMgEADIgBABg");
	this.shape.setTransform(28.5773,29.2988);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#435058").s().p("AjODOQhVhVgBh5QABh4BVhWQBWhVB4gBQB5ABBVBVQBXBWAAB4QAAB5hXBVQhVBXh5AAQh4AAhWhXgAiOgsIgEABIABABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAACIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAAAIAAABIAAACIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAACIAAABIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAAABIAHAAIAMAAICdABIAAACIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAACIAAACIAAABIAAABIAAABIAAAAIAAABIAAABIAAACIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAAAIAAABIAAABIAAABIAAABIAAACIAAABIAAAAIAAABIAAABIAAABIAAACIAAABIAAABIAAABIAAABIAAABIAAABIAAAAIABAAIgBABIAAABIAAABIAAABIAAABIAAABIAAABIAEABIACgCQADgCAKgMQAIgLAMgNIAHgJIAigiIASgWIABgBIABgDIACgDQAAgDgEgDIAAAAQgygtgog0QgFgHgDAEIABAGIgBACIABAFIgBAAIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAADIiegCIgDAAIgDAAIgJABg");
	this.shape_1.setTransform(29.25,29.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,58.5,58.5);


(lib.Símbolo1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.Interpolación2("synched",0);
	this.instance.setTransform(47.65,90.15,1,1,0,0,0,19.5,40.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A39F94").s().p("AgLAsQgGgBgFgDIgBgGIgIgSIgEgKIgEgFIAAgBIgCgEIAAgCIgBgCIgCgIQgCgHABgDIADAAIgBgCQgDgHAAgEQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABAAQACAAABAEQACAIAFAKIABACIACABIACADIAEAFQABAAAAAAQABAAABABQAAAAABAAQAAABAAAAQABgFAJAAIAPABQAKAAAEABQAQAEAKARQACAGgBACQAAABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgMgJgNgHQgMgGgFAFIAEAaQAAAHgCAAQABAEgDADIgFABIgEAAg");
	this.shape.setTransform(51.3107,90.97);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#644459").s().p("AglBmQgngGgagSIgZgTQgQgMgcgQQgRgMgOgDIgSgEQgLgCgFgGQgHgGADgMQACgLAJgHQAGgGAMgFIAUgIIAXgNQAOgHAKgCIgJAJIATgPQAFgEADAAIAEAAIAPgMQARgNAMAEQAAAEgIABQgGABgIAHIgMAMIgFAEQAIgGAGACIgOANIADAAIABABQAFgBAFACIgOAQIACgBIAEAAIAMgLQAKgJAFAFQADADgHAFIgEAEQgBAAAAABQAAABAAAAQAAABAAAAQABABAAAAQAOgKASgBIAWgCQAJgDAOgKQADgBACABQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAQgrAUgVAPIgDACQAAAAABABQAAAAAAAAQABABAAAAQAAABAAABQABADgCADIgBAEIAFgCQADgCACABQAFAAACAGIgBAKQADgCADADIAGAFQADAAAFgEQAMgJAYADQADAAACACQADAEgEAFQgEAEAAAEIALgCIACgCIAEgBIABACIATgGIAmgOQALgEAKgCIAOgEQANgEANgIQANgGAFABIAGAAQADABADgBIACgBIgBgFQAAgFABgCIAFgCIAGgEQAEgBACAHIACAJQgBgEAEgDIAIgCQgBgFAEgCIAHgCIAAgCQgDgDABgEIACgBQgBgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAIAAAAIgDgIQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAIADABIAOAVIAEAGIAEAJIAIASIABAHIAAADIACAHIABADIABAHQADAagaAZQgRATgZAOIgGAFQgGAFgKACIgPAFQgJADgFAAIAAAAQgnAJg3ACIgNAAQggAAgYgEgAB2BYIAEgBIgBAAIgDABgACrATIAAABIABgCgACtARIABAAIAAAAIgBAAgAhlgmIAFAAQAHAAgBAGIADgBQAMgLAMgJQgVAGgRAJgAhrgwIABAAIAAADIADgCIAEgCQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBAAAAIgBgBIgJAGgAh2g4IgBABQgBAEgDABIAAABIAJgJIgEACg");
	this.shape_1.setTransform(25.1955,98.0376);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Símbolo1, new cjs.Rectangle(0,0.1,56.5,108.60000000000001), null);


(lib.Símbolo2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AhsAfIgJgFIgCgCQgCgBgBgEIgBgDQgDgBAAgEIAAgCIAAgBIAAgLIABgDIAAgCQACgJAFgDQAEgDAIgBIAFgBIADAAIABAAQABgBABAAQAAAAABAAQAAAAABAAQAAAAABABIACABQAHADAHAIQAGAIAAAFQABAAAAABQAAAAAAAAQAAABgBAAQAAAAgBABIAAAAIABACIAAAAIAAABIgCAFQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBABIgHAFIgDADIgFADQgGAFgHAAQgEAAgEgCgAhrgOQgFADgDAGIgCAKQAFAMAHACIAJABIAGgCQAEgDAEgEIABgFQAAgEgBgEQgEgKgGgCQgDgCgEAAQgEAAgEACgABdAUIgBgBIgDAAQgHAAgCgBIgEgFIgCgEIgEgGIAAgEIABgCIAAgFIAAgGIADgCIAAgBQADgGAGgEIAGgEIADgBIALAAIAGABIACABIADgBIACABIADACIAHAKQABABAAAAQAAABAAABQAAAAAAABQAAAAgBABIgBACIgBAEIABAGQAAAFgBACQgBACgEACIgEAEIgDABQgGAFgCAAIgFABgABdgYQgIADgEAIQgDAJAFAHQADAFAHACIAEABIAKgCIABgBQAEgEADgEQABgEAAgJIAAAAIgBgDIgHgGIgBgBIgJgBIgFAAg");
	this.shape.setTransform(20.75,30.833);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#55232E").s().p("AAAAWIAAAAIgCgCQgEgCgCgCIgCgDIgCgGIgHgDQgGgCgEgFQgCgFAAgDIAAgBQACgFAIgCIALgCIAIgBIAAAAQAFABAFACIAGAEIADACIAIAEIAGADIAAABIABACIAAADIgBAEIAAAFQgBAGgIAEIAAAAIgBACQAAAAgBAAQAAAAgBAAQAAAAgBABQgBAAgBAAIgDAAQgCABgFAAIgBAAIgFgBg");
	this.shape_1.setTransform(21.8613,46.7895);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#A39F94").s().p("ACPDsIgEgLIAAgEIAEgCIAAgCIADgBIACACIAEAMIAAADQAAABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAIgBACIgBABQgBAAAAgBQAAAAgBAAQAAAAgBgBQAAAAgBgBgAiRjQQgHgEAAgFQAAgDADgCQAAADACAEQAFAGAFACIAIAEIABAFIACADgAhVjUIAAgDIAAAAIAFgBIgBgCIgFAAIgGgDIgIgEIgDgCIgGgEIAGgCQADgDACAAQAFAAADAGIAJgIQAEACgBAEIgFAGIAIAEQAFADgBAEQAAADgDABIgHACIgEADIAAgGgAh8jqIAEAAIgIABIAEgBg");
	this.shape_2.setTransform(33.65,67.9542);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#644459").s().p("AgHAEQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIABgDIAPgEQAAAAABAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAAAIgDACIgGABIgBABIgDABg");
	this.shape_3.setTransform(37.6167,106.5188);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#55232E").s().p("AgCAWIgDgBIAAgBIgDgEQgPgSAAgPIAAgDIACgBIAJgBIAQABQAIACAEAFQACAEADAIIACADIABAKIAAACQgDADgEACIgBABIgBACQAAAAgBAAQAAAAgBAAQAAABgBAAQgBAAgBAAIgDAAQgCABgFAAIAAAAIgCgBg");
	this.shape_4.setTransform(22.4742,46.7875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#A39F94").s().p("ACVD8IgBgCIgDgPIgCgHIgGgLQgCgGABgDQACAAADADIAFALIADAEIADAEIgBADIAAAFIABAKIAAADIgCABIgBAAgAhsi4IgIAAIgFgBIgDgBIgGgDQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABgBQgFgEgDgIIgBgBIgCADQgBADgEgBQgBgBgBgGIgEgIIgBgBQgCgEACgEIACgFIAAgEQAAgEAHgFIAAABIABgBIALgFIAEAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAJAAQAFgBAEABIAKAEIAIAGIAIgHQADACgBAEIgEAGIAHAEQAFADAAAEQAAADgEABIgFACIABAIQAAAFgCAEIgDAEIAFABIACACQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgIACIgGACIgJABIgHAAgAiDjvIgCACIAAACQgBAPAPATIADAEIAAABIAEABIABABIADABIACAAQANgCAFgEIACgDIAAgCIAAgCIgBgKIgCgEQgCgIgDgEQgEgFgHgCIgRgBIgJABgAhRjeIACAAIgBgCIgBAAg");
	this.shape_5.setTransform(33.5461,68.5542);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},10).to({state:[{t:this.shape},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},3).to({state:[{t:this.shape},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},63).to({state:[]},1).wait(13));

	// Capa_1
	this.instance = new lib.Símbolo1();
	this.instance.setTransform(49.1,92.5,1,1,0,0,0,49.1,92.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#A39F94").s().p("AARAiIAAgEIAAAAIADAKIgDgGgAgTgnIAAAAIAAAAIAAAAg");
	this.shape_6.setTransform(0.6,52.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.shape_6},{t:this.instance}]},9).to({state:[{t:this.shape_6},{t:this.instance}]},11).to({state:[{t:this.shape_6},{t:this.instance}]},55).to({state:[]},1).wait(13));

	// Capa_3
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#A39F94").s().p("AgYCXQgHAAgFgEIgFgDIgGgBIgGABQgGAAgHgEQgJgFgFgHIgEgIQgCgGAAgEIAAgBIgBgIIAAgHIAAgDIAEgDIABgBIADgEQAEgFAPgGIAKgFQAHgCAOAAIAHAAIAEgBIACAAIAag1IABgBIAFgLIADgPQAGgqAIgmQAHgagBgMQAAgBAAAAQAAgBABgBQAAAAAAgBQAAAAABgBIgBAAQgBgBABgEQAIgIARACQALAAAEAFQADACACAFQACAFAAAGQABABAAAEIgDATIgQBMIgJAlIgDAKIgIAUQgGAQgRAfQgIANgGAGIgFAEIAAAGIgBAIIgDAHIgFAKIgCAGQgEADgFgCIgFAAIgCACIgCABIgCAAg");
	this.shape_7.setTransform(16.925,77.601);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#A39F94").s().p("AhSB2IgEgCIgDABQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQgGgDgDgFIgDgFQgBgCgDgCIgHgCQgFgCgEgHQgGgJgCgIIAAgJIADgKIAAgBQAAgCADgFIADgGIACgDQAAAAAAAAQABAAAAAAQABgBABAAQAAAAABAAIACgBIAEgBQAGgDAQABIALAAQAHABANAHIAGADIAEABIACAAIAvgjIABgBIAKgHIAJgMQAYgjAZgeQARgVAFgLQABAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQALgEAPAJQAJAFACAHIABAIQgBAFgDAFQACACgCAEIgLAQIgxA8QgOARgLAMQgEAEgCAEIgRAPQgNALgcAUQgMAIgJADIgGABIgCAGQgDAFgCABQgCADgEACIgKAHIgEAEIgCAAQgEAAgDgDg");
	this.shape_8.setTransform(12.075,74.4627);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#A39F94").s().p("AiNAtIgCgFIgDAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBgBABAAQgEgGABgHIAAgFIgCgGQgDgEAAgCQgEgEAAgHQAAgLADgHIAGgIIAIgGIAAgBQABgCAGgDIAGgDIADgBQAAAAAAAAQABAAAAAAQABAAAAAAQABABABAAIACABIAEABQAGAAAOALIAIAFQAGAGAGAMIAEAHIADACIABABIA9gCIAMgBQABAAANgEQAogRAkgLQAagHALgGQABgBAAAAQABAAAAAAQABgBAAAAQABABABAAIgBgBQAAgBABAAQAAAAAAgBQABAAABAAQABAAABAAQALACAHAQQAFAKgDAGQAAADgDAEIgJAHQABACgEABIgTAHIhKAXQgVAHgQAEQgGAAgDADIgWADQgRACgiAAQgPAAgKgCIgFgCIgFADQgFACgDAAQgDACgFgBIgLAAIgGABQgFgCgBgFg");
	this.shape_9.setTransform(9.6417,68.275);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#A39F94").s().p("ABvBJIhNgHQgWgBgQgDQgFgCgEABIgXgGQgQgEgggNQgOgGgIgFIgEgEIgGABIgIgBQgDAAgFgCIgKgEIgGgBQgDgFABgEIgBgGIgCgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAABgBQgCgHAEgGIACgEIABgGQgCgGABgBQgCgGADgHQAEgKAGgGIAIgFIAJgDIABAAIAIgCIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQABABAAAAIACABIADADQAGACAIAQIAGAIQADAIABANIACAIIABADIABACIA5AUIAMADQABABANAAQArAAAmAEQAbADANgBQAAgBABAAQABAAAAAAQABAAAAAAQABAAAAABIAAgBQACgBADABQAKAGAAASQABALgFAEQgBADgFACQgFACgFACQAAABgFABIgUAAg");
	this.shape_10.setTransform(10.131,61.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#A39F94").s().p("ABmBXIhLgSQgugLgVgKQgQgGgegSQgNgHgHgHIgDgFIgGAAIgIgBIgHgEIgKgEQgEgBgCgCQgDgEACgFIAAgFIgCgCQAAAAAAgBQgBAAAAgBQAAAAAAgBQABAAAAgBQAAgHADgFIADgEIABgGIAAgGQAAgGAEgHQAFgJAHgFIAJgEIAKgCIAAAAIAIgBIAHAAIADAAIADAEIABABIAEAEQAFAEAGAPIAEAJQACAIAAAOIAAAHIABAEIAAABIA1AcIAMAGIAOADQArAGAlAKQAaAGANAAQAAAAABAAQABAAAAAAQABAAAAABQAAAAABAAIAAAAQABgBAAAAQABAAAAAAQABAAAAABQABAAABABQAIAHgCASQgBAKgFAEIgHAFQgFABgFAAQgBACgFAAIgTgDg");
	this.shape_11.setTransform(9.724,58.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#A39F94").s().p("AgfA7QgSgCghgKQgPgEgHgEIgFgEIgGABQgFACgDgBIgIgBIgLgDQgDAAgDgBQgDgEgBgFIgBgFIgCgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQgCgHACgFIACgEIgBgGIgCgGQgBgFACgIQACgLAGgGQABgCAGgEQAFgDAFgBIAAgBIAHgDIAKgCQAAAAABABQAAAAAAAAQABAAABABQAAAAABABIABABIAFACQAGADAKANIAGAIQAEAGADAOIACAHIACAEIAAAAIA7AOIANACIAPgBQAqgEAngBQAbAAAMgEQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAIAAgBQACgCADABQAKAGADARQABAKgDAGIgGAGIgJAEQgBACgFABIgTACIhNACIgUABQggAAgSgDg");
	this.shape_12.setTransform(9.6275,61.2611);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#A39F94").s().p("AiIAyQgEgCgCgEIgDgFIgCgBQAAAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQgEgHABgFIAAgFQAAgDgCgDIgDgGQgDgEAAgHQAAgLADgHIAGgIIAIgHIAAgBIAGgEIAJgFQAAAAABAAQAAAAABABQAAAAABAAQABABAAAAIACABIAFABQAHABANAKIAIAGQAFAFAHAMIADAGQABABABAAQAAABAAAAQABABAAAAQAAABAAAAIABAAIA8gBIANgBIAOgFQAogPAmgLQAZgHALgHQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAABIAAgBQABgCAEAAQALADAHAPQAEAKgCAHIgEAHQgDAEgFACQAAACgEABIgSAHIhKAWQgvAOgVADQgSACgjgBQgPAAgIgBIgGgDIgGADQgEACgDAAQgCABgGAAIgLAAIgDABIgDgBg");
	this.shape_13.setTransform(8.6583,66.35);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#A39F94").s().p("ABvBJIhNgHQgwgEgVgGQgRgEghgOQgOgFgHgFIgEgEIgHAAQgFABgDgBIgHgCIgLgEQgDAAgCgCQgDgEAAgFIgBgFIgCgCQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQgBgHADgFIACgEQABgCgBgEIgBgHQgBgFADgIQAEgKAGgGIAIgFQAFgCAFgBIABgBIAHgBIAJgBQABAAAAAAQABAAAAABQAAAAABABQAAAAABABIACABIAEACQAFAFAJANIAFAIQADAHADAPIAAAHQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAIABABIA4ATIANAEIAPABQAqAAAnAEQAbADAMgCQABAAAAAAQABgBABABQAAAAAAAAQABAAAAAAIAAAAQACgCAEACQAJAHABARQAAAKgEAFIgGAFQgFADgFAAQgCACgEABIgHAAIgMAAg");
	this.shape_14.setTransform(10.1107,59.9125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#A39F94").s().p("AiHAyQgFgDgCgEIgDgEIgCgBIgCgDQgEgHABgFIAAgFQAAgCgCgEIgDgFQgDgFAAgHQgBgLAEgIIAFgIIAJgGIAAgBIAGgEIAJgFQABAAAAAAQAAAAABABQAAAAABAAQABABAAAAIADAAIAEABQAHADANAJIAHAFQAGAGAIAMIACAHQABAAABABQAAAAAAAAQABABAAAAQAAABAAAAIABAAIA8gCIAOAAIANgFQAogQAmgKQAZgHALgGQABgBAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAAAAQABgCAFAAQAKADAHAQQAEAJgBAGIgFAHQgDAEgFADQgBACgDABIgSAHIhKAWQgvAOgVACQgSADgjgBQgPAAgIgCIgGgCIgGADQgEADgDAAIgIAAIgLAAIgDABIgCgBg");
	this.shape_15.setTransform(8.9072,67.3125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#A39F94").s().p("ABmBXIhLgRQgvgNgUgIQgRgHgdgSIgTgNIgEgFIgHAAQgFAAgDgCIgHgEIgKgEQgBAAAAAAQgBAAgBgBQAAAAAAAAQgBgBAAgBQgDgEABgFIgBgEIgBgEIgBgDQABgHADgEIADgEIABgHIgBgGQABgFADgIQAFgJAIgFIAIgFIALgBIABgBIAHAAIAKABIADAEIACABIADACQAEAGAHAPIAEAIQACAHABAPIgCAHQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAIABABIA1AbIAMAHIAOACQArAHAlAKQAaAHAMAAQADgBACACIAAgBQACgCADADQAIAIgCARQgBAKgEAFIgIAEQgFABgFAAQgCACgEAAQgFAAgOgDg");
	this.shape_16.setTransform(11.0048,58.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#A39F94").s().p("AgaA4QgSAAgigHQgPgDgHgDIgGgDIgGACQgFACgDgBIgIgBIgLgCQgEABgBgCQgEgEgBgDIgCgFIgDgCIgBgEQgCgGABgGIACgEIgCgGIgCgFQgCgGABgIQACgKAFgIIAHgGQAFgEAEgBIABgBIAGgDIALgDIADADIACAAIAEABIASAQIAGAHQAFAGAFANIABAHQABABAAAAQAAABABAAQAAABAAAAQAAAAAAAAIABABIA8AIIANACIAOgCQArgIAngCQAagDALgEQADgCACABIAAAAQABgCAEABQAKAFAEAPQADAKgDAGIgGAGQgDADgGACQgBACgDACIgTADIhNAKQgiADgUAAIgQgBg");
	this.shape_17.setTransform(10.1756,62.7808);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#A39F94").s().p("ABrBtIgTgHIhHgeQgsgVgRgMQgQgJgagYQgLgIgFgHIgDgFIgHgBQgFgBgCgDQgCAAgFgEIgIgIQgEAAAAgDQgCgFABgEIABgFIgBgDIAAgEQACgGADgFIAEgCIACgHIABgGQABgGAFgGQAHgIAIgEIAJgCQAGgBAEABIACAAIAHAAIAKADIACAEIABABIADADQAEAHADAQIADAIQABAIgCAPIgDAGQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIABACIAwAjIAKAKIANAEQAqAPAjARQAYAKAMACQADAAABACIAAAAQADgBADADQAGAJgGAQQgCAKgFAEIgIACQgFABgGgCQAAAAgBABQAAAAgBAAQAAAAgBABQgBAAAAAAIgBAAg");
	this.shape_18.setTransform(11.0482,56.8967);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#A39F94").s().p("AgZA4QgTAAgigHQgOgDgIgEIgGgCIgGACQgFACgDgBIgIgBIgKgDQgFACAAgCQgFgEgBgEIgBgEIgEgCIgBgEQgCgGABgGIACgEIgCgGQAAgCAAAAQAAgBgBgBQAAAAAAgBQAAAAgBAAQgCgGABgIQACgKAFgIIAHgGIAJgFIABgBIAHgDIAKgCIADACIACAAQABAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAHAEAKAMIAHAFQAFAGAFAOIACAHQAAABABAAQAAABAAAAQAAABAAAAQAAAAAAAAIABABIA8AIIANADIAOgDQArgIAngCQAagEALgEQADgBACABIAAAAQABgCAFABQAJAEADAQQADAKgCAGQgCACgDAEIgKAFQgBACgDABQgGACgNACIhNAJQgjAEgUAAIgOgBg");
	this.shape_19.setTransform(7.86,63.9994);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_7}]},10).to({state:[{t:this.shape_8}]},3).to({state:[{t:this.shape_9}]},3).to({state:[{t:this.shape_10}]},3).to({state:[{t:this.shape_11}]},8).to({state:[{t:this.shape_12}]},10).to({state:[{t:this.shape_13}]},3).to({state:[{t:this.shape_14}]},3).to({state:[{t:this.shape_15}]},3).to({state:[{t:this.shape_16}]},3).to({state:[{t:this.shape_17}]},3).to({state:[{t:this.shape_18}]},3).to({state:[{t:this.shape_19}]},3).to({state:[]},3).wait(29));

	// pierna2
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#A39F94").s().p("AgtBkIABAAIgBABIAAgBgAg8BYQgJgCgjAAQgPAAgHgCIgJgDIgIgDIgGgDQgEgDABgDIABgEQAJgFAUgFQBCgPAwgpIA1gzQAdgaALgVQAFgBAGABIANADIAQABQAKAAAGACQAJADACAGQADAHgJALIgGAGQgQAFgYANIgNAIQgHAFgLAMQgMAMgaAVQgSASgOAXIgJAPQgFAIgGAFQgHAFgJACIgFABQgIgDgKgCgAgpAQIAAAAIAAAAg");
	this.shape_20.setTransform(-1.2421,107.9594);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#A39F94").s().p("AhHBPIABABIgBAAIAAgBgAhSA/IgqgMQgPgEgGgEQgFgCgDgDIgMgKQgDgEACgDIABgDQALgCAUAAQBEACA5gaIBBgkQAigSARgRQAFgBAFADIALAHIAQAFQAKADAFADQAIAFAAAGQABAJgLAHIgHAFQgSABgaAGIgOAFQgIACgOAKQgPAHgeAOQgXAMgUATIgMAMQgHAHgHADQgIADgJgBIgFABQgHgGgJgFg");
	this.shape_21.setTransform(-3.3991,105.9875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#A39F94").s().p("AhRAzIgFgBQgFgHgIgHQgHgFgegSQgNgHgGgGIgFgGIgGgGIgDgGQgDgFADgCIACgDQALABATAFQBCAUA+gMIBHgRQAmgJAUgMQAFAAAFAFIAKAJIANAJIANAJQAHAIgCAGQgBAHgNAEIgIADQgRgEgbgBIgPABQgJABgPAFQgRAEghAGQgYAGgZANIgPAJQgIAEgIABIgFAAQgGAAgGgCg");
	this.shape_22.setTransform(-4.7734,103.3475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20,p:{regX:0,regY:0,x:-1.2421,y:107.9594}}]}).to({state:[{t:this.shape_21}]},18).to({state:[{t:this.shape_20,p:{regX:8.5,regY:-10,x:7.3,y:97.95}}]},13).to({state:[{t:this.shape_22}]},17).to({state:[{t:this.shape_22}]},28).to({state:[]},1).wait(13));

	// pierna
	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#A39F94").s().p("AhyBnIgCgDQADgGAGgGIAKgHIARgIIAFAAIAMgEIADgBQAHgCAJgIQASgNAJgJQANgOARgkIAHgRIABgGQAMgVAKgZQACgHADgDQAEgGAKgDQAVgHAXAFQAFABADADQAEADgBAGQgBAHgFAGIgBAEQgGAKgLARIgSAbQgGALgJATIgDAHIgFAIIgKAMQgPATgSAiIgGAGIgEADIgDgBIgKAHIAAAAIgHAAIgOgBIgJgDIgJAAQgNAAgHACQgGgCgHADIgBABIgEAAIgMACIgCAAQgGAAgDgEgAARBIIACgDIgBAAIgBADgABuhcIABAAIAAAAIgBAAgAAEgLIABgCIgBACg");
	this.shape_23.setTransform(12.91,111.142);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#A39F94").s().p("AguBZIgOgFIgIgFIgIgDQgMgDgIABQgGgEgHABIgCABIgDgBIgNgBQgHgBgCgGIgBgEQAEgEAIgFIALgEIATgDIAFABIAMgBIADAAQAIAAALgFQAUgIALgHQARgKAZgeIALgPIADgEQARgSAQgWQAEgHAEgBQAFgFAKAAQAXgCAUALQAGACABAEQADAEgDAGQgCAGgGAFIgCADIgYAWQgRAOgHAIQgJAHgNARIgGAHIgGAGIgNAJQgUAOgZAcIgHAEIgGACIgCgBIgLADIgHgBgAAABDIABgBIAAgBQgBAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAgACDhDIABABIAAgBIgBAAgAAIgQIABgBIgBABg");
	this.shape_24.setTransform(11.9442,111.166);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#A39F94").s().p("AguBZIgOgFIgIgFIgIgDQgMgDgIABQgGgEgHABIgCABIgDgBIgNgBQgHgBgCgGIgBgEQAEgEAIgFIALgEIATgDIAFABIAMgBIADAAQAIAAALgFQAUgIALgHQARgKAZgfIALgOIADgEQARgSAQgWQAEgHAEgBQAFgFAKAAQAXgCAUALQAGACABAEQADAEgDAGQgCAGgGAFIgCADIgYAWQgRAOgHAIQgJAHgNARIgGAHIgGAGIgNAJQgUAOgZAcIgHAEIgGACIgCgBIgLADIgHgBgAAABDIABgBIAAgBQgBAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAgACDhDIABABIAAgBIgBAAgAAIgQIABgBIgBABg");
	this.shape_25.setTransform(12.0442,109.416);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23,p:{regX:0,regY:0,x:12.91,y:111.142,rotation:0}}]}).to({state:[{t:this.shape_24}]},21).to({state:[{t:this.shape_23,p:{regX:8.9,regY:-4.2,x:21.8,y:106.9,rotation:0}}]},16).to({state:[{t:this.shape_23,p:{regX:8.8,regY:-4.2,x:21.7,y:106.95,rotation:14.9992}}]},17).to({state:[{t:this.shape_25}]},22).to({state:[]},1).wait(13));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21.9,0,78.4,121.9);


// stage content:
(lib.cuento_macabro = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [91,103,201,216,263,274,318,328];
	// timeline functions:
	this.frame_91 = function() {
		/* Hacer clic para ir al fotograma y reproducir
		Al hacer clic en la instancia del símbolo especificado, la cabeza lectora se mueve hasta el fotograma especificado en la línea de tiempo y prosigue la reproducción desde dicho fotograma.
		Se puede utilizar en la línea de tiempo principal o en líneas de tiempo de clips de película.
		
		Instrucciones:
		1. Reemplace el número 5 del siguiente código por el número de fotograma hasta el que quiere que se mueva la cabeza lectora cuando se haga clic en la instancia del símbolo.
		2.Los números de fotograma en EaselJS empiezan con 0 en vez de 1
		*/
		
		this.button_4.addEventListener("click", fl_ClickToGoToAndPlayFromFrame_3.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame_3()
		{
			this.gotoAndPlay(105);
		}
	}
	this.frame_103 = function() {
		/* Detener en este fotograma
		La línea de tiempo se detendrá/pausará en el fotograma en el que se inserte este código.
		También se puede utilizar para detener/pausar la línea de tiempo de clips de película.
		*/
		
		this.stop();
	}
	this.frame_201 = function() {
		/* Hacer clic para ir al fotograma y reproducir
		Al hacer clic en la instancia del símbolo especificado, la cabeza lectora se mueve hasta el fotograma especificado en la línea de tiempo y prosigue la reproducción desde dicho fotograma.
		Se puede utilizar en la línea de tiempo principal o en líneas de tiempo de clips de película.
		
		Instrucciones:
		1. Reemplace el número 5 del siguiente código por el número de fotograma hasta el que quiere que se mueva la cabeza lectora cuando se haga clic en la instancia del símbolo.
		2.Los números de fotograma en EaselJS empiezan con 0 en vez de 1
		*/
		
		this.button_3.addEventListener("click", fl_ClickToGoToAndPlayFromFrame_2.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame_2()
		{
			this.gotoAndPlay(218);
		}
	}
	this.frame_216 = function() {
		/* Detener en este fotograma
		La línea de tiempo se detendrá/pausará en el fotograma en el que se inserte este código.
		También se puede utilizar para detener/pausar la línea de tiempo de clips de película.
		*/
		
		this.stop();
	}
	this.frame_263 = function() {
		/* Hacer clic para ir al fotograma y reproducir
		Al hacer clic en la instancia del símbolo especificado, la cabeza lectora se mueve hasta el fotograma especificado en la línea de tiempo y prosigue la reproducción desde dicho fotograma.
		Se puede utilizar en la línea de tiempo principal o en líneas de tiempo de clips de película.
		
		Instrucciones:
		1. Reemplace el número 5 del siguiente código por el número de fotograma hasta el que quiere que se mueva la cabeza lectora cuando se haga clic en la instancia del símbolo.
		2.Los números de fotograma en EaselJS empiezan con 0 en vez de 1
		*/
		
		this.button_2.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame()
		{
			this.gotoAndPlay(276);
		}
	}
	this.frame_274 = function() {
		/* Detener en este fotograma
		La línea de tiempo se detendrá/pausará en el fotograma en el que se inserte este código.
		También se puede utilizar para detener/pausar la línea de tiempo de clips de película.
		*/
		
		this.stop();
	}
	this.frame_318 = function() {
		/* Hacer clic para ir al fotograma y detener
		Al hacer clic en la instancia del símbolo especificado, la cabeza lectora se mueve hasta el fotograma especificado en la línea de tiempo y detiene la película.
		Se puede utilizar en la línea de tiempo principal o en líneas de tiempo de clips de película.
		
		Instrucciones:
		1. Reemplace el número 5 del siguiente código por el número de fotograma hasta el que quiere que se mueva la cabeza lectora cuando se haga clic en la instancia del símbolo.
		2.Los números de fotograma en EaselJS empiezan con 0 en vez de 1
		*/
		
		
		this.button_5.addEventListener("click", fl_ClickToGoToAndStopAtFrame_5.bind(this));
		
		function fl_ClickToGoToAndStopAtFrame_5()
		{
			this.gotoAndStop(0);
		}
	}
	this.frame_328 = function() {
		/* Detener en este fotograma
		La línea de tiempo se detendrá/pausará en el fotograma en el que se inserte este código.
		También se puede utilizar para detener/pausar la línea de tiempo de clips de película.
		*/
		
		this.stop();
		
		
		
		/* Hacer clic para ir al fotograma y reproducir
		Al hacer clic en la instancia del símbolo especificado, la cabeza lectora se mueve hasta el fotograma especificado en la línea de tiempo y prosigue la reproducción desde dicho fotograma.
		Se puede utilizar en la línea de tiempo principal o en líneas de tiempo de clips de película.
		
		Instrucciones:
		1. Reemplace el número 5 del siguiente código por el número de fotograma hasta el que quiere que se mueva la cabeza lectora cuando se haga clic en la instancia del símbolo.
		2.Los números de fotograma en EaselJS empiezan con 0 en vez de 1
		*/
		
		this.button_6.addEventListener("click", fl_ClickToGoToAndPlayFromFrame_4.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame_4()
		{
			this.gotoAndPlay(0);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(91).call(this.frame_91).wait(12).call(this.frame_103).wait(98).call(this.frame_201).wait(15).call(this.frame_216).wait(47).call(this.frame_263).wait(11).call(this.frame_274).wait(44).call(this.frame_318).wait(10).call(this.frame_328).wait(1));

	// Capa_5
	this.instance = new lib.CachedBmp_18();
	this.instance.setTransform(537.5,414.6,0.5,0.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(318).to({_off:false},0).wait(11));

	// botones
	this.button_4 = new lib.boton1();
	this.button_4.name = "button_4";
	this.button_4.setTransform(582.2,429.2,1,1,0,0,0,29.2,29.2);
	new cjs.ButtonHelper(this.button_4, 0, 1, 1);

	this.button_3 = new lib.boton2();
	this.button_3.name = "button_3";
	this.button_3.setTransform(582.2,429.2,1,1,0,0,0,29.2,29.2);
	new cjs.ButtonHelper(this.button_3, 0, 1, 1);

	this.button_2 = new lib.boton3();
	this.button_2.name = "button_2";
	this.button_2.setTransform(582.2,429.2,1,1,0,0,0,29.2,29.2);
	new cjs.ButtonHelper(this.button_2, 0, 1, 1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#435058").s().p("AjaDbQhbhbAAiAQAAiABbhaQBahbCAAAQCAAABbBbQBbBaAACAQAACAhbBbQhbBbiAAAQiAAAhahbg");
	this.shape.setTransform(568.5,425.95);

	this.button_6 = new lib.Símbolo4();
	this.button_6.name = "button_6";
	this.button_6.setTransform(568.5,425.95,1,1,0,0,0,31,31);
	new cjs.ButtonHelper(this.button_6, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.button_4}]},91).to({state:[]},13).to({state:[{t:this.button_3}]},97).to({state:[]},16).to({state:[{t:this.button_2}]},46).to({state:[]},12).to({state:[{t:this.shape}]},43).to({state:[{t:this.button_6}]},10).wait(1));

	// barca
	this.instance_1 = new lib.Interpolación1("synched",0);
	this.instance_1.setTransform(190.95,356.3);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(104).to({_off:false},0).to({_off:true},113).wait(112));

	// salpicadura
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCCCCC").s().p("AhvBrIgDgBIgBAAIgBgBIgBgDQAAgDADgCQACgEAEAAQAAAEAFAIIgFABIgCABgAjwBZIgGgFIgHgBQgHgCgLgFIAAgDIABgBQAMACASAJQAGADABAEIgCAAIgFgBgAjOBVIAAgBIgCgGIgEgBIgBgEIADgBIAAgBIAHACIABAIIAEAEIgCACQgEAAgCgCgACcBSQALgHANgCIACgBIAVABQAAABABAAQAAAAgBABQAAAAAAAAQAAABgBAAIgDABQgPAAgHACQgQAGgIABQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBABAAgABxBLIAOgPQALgNAXgPQAKgGAFACQAAADgDACIgFABQgGABgFAFIgKAIQgLAGgEAFIgJANQgEAHgGACQgCgCACgEgAAqA7QAAgPAEgIIAEgJIACgEQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABABQAAADgGAOQgDAJAAASIgBAEQAAAAgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQgCgGABgGgAlCA1IgOADIgBgFQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIAAgBIARABQABAFAAAEIgBACQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABgBAAQgCgEABgEgAjtAeIAAgDIABgCIABgBIAEgCIADAEIgEAEIAAACIgBAEIAAABIgDABQgBgCAAgGgADhAjIgCAAIgGgFIAEgDIADADIACgCIgEgDIACgCIAAgBIAJABIgBAGIgBAGIgFAAIgBAAgAEbAfIABgEIACgBIADgDIADgDQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAIAAAEIgCACIgCAEIgDAEgACngQQAEgDAFgGIABgCIAAgCQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIAAgBIAHABIgHAIIgDAEIgHAGgAFOgfIgHgBQgSgEgQgCIAAgDQABAAAAAAQAAAAAAAAQABAAAAgBQgBAAAAAAQAUAAAUAGIADABQADADgDADQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAgAFCheIAFgEIACgBIABgCIACgEQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAQAAADgBADIgBACIACADIgCADIgFAEg");
	this.shape_1.setTransform(381.075,362.4938);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCCCCC").s().p("AhHCGIgDAAIgBgBIgBAAIgBgCIAAgBQAFgDACgDIACAAQABADAEAGIgFABIgCABgAjIB0IgGgEIgBAAIADgCIAHAHIAAABIgDgCgADEBtIADgCIADAFIgJACQAAgBAAAAQAAgBABgBQAAAAAAgBQABAAABgBgADLBqQAIgEAJgBIACgBIAVABQAAABABAAQAAAAgBABQAAAAAAAAQAAABgBAAIgDABQgPAAgHACIgKADIgEgEgACZBnIAJgKIAAAHIAAACQgEAFgFABQgCgCACgDgAjnBlIAAAAIAAAAgAkaBRIgOACIgBgEQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIAAgBIARABQABAEAAAFIgBACQAAAAgBABQAAAAAAAAQAAAAgBAAQAAAAgBAAQgCgDABgEgABXBGIAEgHIgBADQgCAGgBALQgBgKABgDgAmhBQIgBgEQAAgBAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQABgBAFAAIAWAFQAAABAAAAQAAABAAAAQAAABgBAAQAAAAgBAAIgEABIgGABIgRgBgAGJBPIgCgBIAAgCIAAgKIAGgDIAEAGIABACIgBAIIgFAAIgCABgACyBNIAPgMIgBAGIgFAFIgHADIgCgCgADJA+IAAACIgBABIABgDgAEJA/IgCgBIgGgEIAEgDIADADIACgCIgEgEIACgBIAAgBIAJABIgBAGIgBAFIgFABIgBAAgADOA8IgBgCQAHgEAEACQAAADgDACIgFABIgBAAIgBgCgAFDA7IABgEIACgBIADgDIADgEQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAAAEIgCACIgCAEIgDAEgABaA2IACgDQAAgBABgBQAAAAABAAQAAAAABgBQAAAAABABIgCAHIgGADgAjFA3IABgCIABgBIAEgCIABABIAAABIgGAGIgBABgAG7ATIgEAAIgBgCIgBgDQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIAAgBIAGABIACAAIAEAEIAAADQgDAAgDABIgBABgADPALQAEgDAFgHIABgBIAAgBQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIAAgBIAHABIgHAHIgDAEIgHAGgAkzABIAAgHIgBgCIgIgCIAAgDIABAAIAAgBIAIACIAEADQABABAAAHIAAACIgDADgAF2gDIgHgBQgSgFgQgBIAAgDQABAAAAAAQAAAAAAAAQABAAAAgBQgBAAAAAAQAUAAAUAFIADABQADADgDAEQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAgAnNgTIgNgBQgDgCgFgFQAAAAAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIAAgBIAHABIABACIAOADQAAABAAABQAAAAgBABQAAAAAAABQAAAAgBAAgAFqhCIAFgFIACgBIABgBIACgEQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAQAAACgBAEIgBABIACAEIgCADIgFADgAHYh3IgBgGQAAgFAEgCQABAAAAAAQAAgBABAAQAAAAAAAAQAAgBAAAAIADAAIACACIABACIgBADIgCACIgEAGg");
	this.shape_2.setTransform(377.075,359.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCCCCC").s().p("AhYCdIgDAAIgBgBIgBgBIgBgCIAAAAQAFgDACgEIACAAQABAEAEAFIgFACIgCABgAjZCLIgGgEIgBgBIADgBIAHAHIAAABIgDgCgACzCEIADgCIAEAEIgKACQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABgBgAC6CAQAJgDAIgBIACgBIAVABQABAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABIgDABQgPAAgHABIgKAEIgEgFgACIB9IAJgJIAAAHIAAABQgEAGgFABQgCgCACgEgAp0B2IAAgCIgDgCQgEAAgEgEIABgCQADAAACgCIAJAIIABAEIAAAFQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQgCgDAAgFgAj4B8IABgBIgBABgAkrBoIgOACIgBgEQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAAgBIARABQABAEAAAEIgBADQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAQgCgDABgEgABGBcIAEgGIgBADQgCAGgBAKQAAgJAAgEgAmyBnIAAgCIAAgBIADgGIAEAAIAPADIgFAHIgRgBgAmbBnIAEgFIACABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAgBAAIgEABgAF4BmIgCgCIAAgBIAAgKIAGgDIAEAFIABADIAAACIgBAFIgFABIgCABgAChBjIAQgMIgCAHIgFAEIgHAEIgCgDgAgJBgIgBgHIgCgDIAFAAIACAGQACAGgEAEQgCgCAAgEgAivBYIAAACIgBAAIABgCgAizBYIAAgBIgBgFIgCgDIADgCIACAFIABAEIgCAAIgBADgAC4BVIABACIgCABIABgDgAD2BVIgGgFIAEgCIADACIACgBIgEgEIACgBIAAgBIAFAAIgBAFIgCABIgDAHgAC9BTIgBgDQAHgDAEACQAAACgDACIgFABIgBABIgBgCgAhoBTQgBgEAAgPIAIgBIACgGQABgEAEABIABAGQABAIgCAIQgIAAgCAHgAEyBRIABgDIADgCIAAACIAAAEgABJBNIACgEQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAIgCAHIgGADgAjWBOIABgCIABgCIAEgBIABABIAAAAIgGAGIgBABgAE5BJIACgDQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIAAAEIgCABIgCAFIAAABIgCgHgAD/BPIABgFIAAAAIgBAFgAgOBOIAAgJIAAgZIABgEQAAgBABAAQAAgBABAAQAAAAAAAAQABAAAAABIABAYIAAAPIgFAAgAi5BKIgBAAIgFgNIABgFIABgDIAIAUIgDADIgBgCgAJ3AzIgFgHIgDgDQgCgDAAgEIADAAIAGAJIACACQADABAEgCQABAEgBADgAGqAqIgEAAIgBgCIgBgEQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAAgBIAGABIACAAIAEAEIAAADQgDAAgDABIgBABgAC+AiQAEgDAFgHIABgCIAAgCQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAAgBIAHABIgHAIIgDAEIgHAFgAlEAYIAAgIIgBgCIgIgDIAAgCIABAAIAAgBIAIABIAEAEQABABAAAHIAAADIgDACgApWAPQgBgBgGABIgLABIgDgHQACgCAHgBIAIAAIADgBIAFgBIABALQAAAFgCABQgEgCABgEgAFlATIgHgCIgGgBIgBgCQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAAAgBABIAAAAIgFgBIAAgBIAAgFQALACALADIADABQADADgDADQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAgAFHANQgCgEgEgBIgDAAIgBAAIANAAIAAAFIgDAAgAE8AJIABAAIgBAAgAnfADIAAgEIAEABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAgAnrABQgDgBgFgEQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAAgBIAHABIABACIAFABIAAAEgAB3gFQgDgCAAgDQAEgEAAgBIAAgCIABgDIADgEIABgBQABAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAAAIACADIAAAMIgCACIgCAEIgCACIgBAAIgDgCgAAUgOIgFgFQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAAgBIAMABIgEAFQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgBABQAAAAgBgBQAAAAAAAAQgBAAAAAAQAAgBAAAAgAFZgsIAFgEIACgBIABgCIACgDQABgBAAAAQABAAAAAAQAAAAABAAQAAAAABAAQAAACgBAEIgBABIACADIgCAEIAAAAQgFgBgBADgAgcg1IgBgQIAAgJIAFABQAAARgBAHgAgdhUIAAgIIABgNIADgLIABgDQABgBAAAAQABAAAAAAQABgBAAAAQABABAAAAQABADgDAHQgDAKABARIgFgBgAHHhgIgBgGQAAgFAEgCQABAAAAgBQABAAAAAAQAAAAAAgBQAAAAAAAAIADAAIACACIABACIgBADIgCACIgEAGgABghoIACgFIADgNIADgIQABgEAAgFQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQACAFgCAFIgDAGIgCAIIgEAOQgCAEgCAAQgCgCACgEgAlOiCIABgEIACgEQACgDAAgJQgDABgDAFIgIANQgDAEgCAAQgCABgEgDIAFgHIAGgGIAMgNQABAAAAgBQAAAAAAAAQAAAAAAAAQAAgBgBAAIALACQgBADgDAEIgBAGIgCAHQgBAEADACIgCADQgGgBgBgDgADXiRIADgGIABgCIACgCIADAAIABAGIAAABIgBABIgHAEg");
	this.shape_3.setTransform(378.7625,357.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CCCCCC").s().p("AjcBUIgCgCIgKgTQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAABIAIAOQADAFgBADIgBAAIgBAAgABrBIIALgJQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAAgBIAPABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABIgFABQgKAAgKAHgAEMBGIgIgBIAAgDIAEgBIAPgBIAHgCIAAgBIANABQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAABIgFABIgJABIgIACIgDAAIgEAAgAn0BDIgCgEIgCgDQgBgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQgGgCgEgFIABgCQACgBADACIAFAEIACACIACADIADAGQACADgBADIgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBgAhIA8IABgHIABgDIAAgDIAFgBIACADIgDAEIgBADIAAAJIgBADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgCgDAAgGgAlfA4QgGgJgGgDQgFgCgIgBIgOgCQAAAAgBgBQAAAAABgBQAAAAAAAAQAAgBABAAQAUgBAJAGQAFADAHAKIAKANIgBACIgMgNgApDATIgEgCIgDACIgEgBQgBgDACgDIABAAIAAgBIAPAAIACADIgEAEIgCABIgCAAgAEhgZQAAgDAEgEIAHgEIAEgEIAHgDIADADIgJAFIgMAJQAAAAAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAIgBAAgAAvgsIAAgSIABgDIACgCIADgEQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAIADADQAAACgDACIgDAEIgBADIAAASIAAAEQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQgCgCAAgHgAJBhOIABgDQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAAgBIALABIAAADIgCABIgHACIAAAGIgBACIgCABQgCgCAAgJg");
	this.shape_4.setTransform(369.02,361.6333);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},154).to({state:[{t:this.shape_2}]},2).to({state:[{t:this.shape_3}]},2).to({state:[{t:this.shape_4}]},2).to({state:[]},2).to({state:[]},55).wait(112));

	// agua
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#236BC0").s().p("AgnBVQgjgHgSgZIgMgXQgIgPgGgHQgLgKgbgMQgmgSgXgFQgSgFgagBIgtgCIgvgFIgwgEQgngDhNAEIhuAGQgZABgJgIQgIgGACgLIABgEIgdAAIAAgCIABAAIAAgCIAdAAQADgDAFgBQgDACgBACIOvACIAGgGQAFgEADAAIACADIgIAHIGWAAIAAACIgBABImaAAIgGAFIgQACIAFADQgNgBgOAKIgEAEIgbAaQgNANgWAMIgnAXIg3AhQggATgZAIQgTAFgRAAQgOAAgNgDg");
	this.shape_5.setTransform(383.375,380.2735);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#236BC0").s().p("Ah6BiIghgCQgUgBgQgDIgNgDIAAAAQgaAAgOgCQgWgFgNgMQgFgEgHgLQgGgJgEgOIgHgUIgDgGIgHgGIgNgHIgNgKQgOgPAGgOQACgEAGgFIgCgDIAEgCIgLgBIgwgFQgngChNAEIhuAFQgZABgJgIQgIgGACgKIABgEIgdAAIAAgDIABAAIAAgBIAdAAQADgEAFgBQgDACgBADIOvABIAGgFQAFgFADAAIACAEIgIAGIGWAAIAAADIgBABImaAAIgGAFIgQABIAFADQgNAAgOAKIgEADIgbAaQgNANgWAOIgnAVIg3AiQggATgZAHIgHACIgIAJQgUASgdgBQgIgBACgEIgSgBQgOAFgLABIgNABIgUgCgAhmBbIAMAAIgBgFIgHADQgFACgIgBIgIAAIARABgAkmAeQAJARAFAIQAJANAMAGQAKAGAWABQgOgHgMgJQgLgJgVgYIgQgRgAlagmQAAAHAIAIQAGAFAMAJIgUgnQgFAGgBAEg");
	this.shape_6.setTransform(383.375,381.4071);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#439BED").s().p("AkpBlIAAAAQg8gGg6AAQAAAAAAgBQAAAAAAAAQAAAAAAgBQABAAAAgBIAEgBIA6AAQAcABApAGIAEABIABAAQABABAAAAQABABAAABQAAAAAAABQgBAAAAABIgUgDgAjQBXIg9gEIgZACIAAgEIABgBIgLAAQAAgEAGAAIAZABQAPgBATABIA3ABQADACgGABIgEABIAJAAQAPACAHAFIgwgCgAm5A3IgWAAQgGAAgCgDQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQADACAGAAIASAAICaACQAAABAAAAQAAABAAAAQAAAAAAABQAAAAgBAAIgDABgAGNApQgQgBgFgGQABgBAAAAQABgBAAAAQABAAAAAAQABAAABAAQADADAHAAIAjACQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABIgEABgAEQAlIiagIQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAABgBIACgBIB8ABQAXABAJAFQABAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAIgDABIgBAAgAElAeIAAgCIADgBIBngHQANAAAMgDIACADQgIAIgWgBIgzADIgdABIgXgBgAkcAaQgPgBgagGQAAgDAFAAIARAAIAnAAQAQgBAIgBQAPgDAHACQgGAHgIgBQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAIAAABIgGAAgAjuABIgNgBIAAgBIABAAIAAgBIAbAAIAHABQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABgBAAIgEAAgAkOgRQABAAABAAQAAAAABgBQAAAAABAAQAAAAABAAIBegFIBdgEQAAABAAAAQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgxAEgwACQgtACgsABQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAgBgAlAgSIhGgBIgBgEIABgEIAjAAIAQAAIAAACIACABIADAAIAlAAQAQABAJgEQgggHgfAAQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAgBIAEAAQAmAAAsAGQAAADgFACQgXAJgkAAIgIgBgAGqhSQAPgGARgDIgCgEIhdgEQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAABAAIADgBIBLABQAWAAAIAJQgUAMgYAAQgEABACgDg");
	this.shape_7.setTransform(350.1,383.55);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#238DDE").s().p("AlDBSIgUgBIgdAAQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBABAAIAagBIAEguICWACIAEgBQAAgBAAAAQABAAAAgBQAAAAAAgBQgBAAAAAAIiagDIADgfIABgNQgfABgRgGQABgDAGAAIAqgBIATAAQAkgBAYgHIhNgCIgegBQgCgDAEgCQADgCAEAAIAXgBIApgBIACAEIBFACQAqABAZgKQAFgCAAgDQgsgGgmAAIgDABQgBAAAAAAQAAABgBAAQAAAAAAABQAAAAABAAQAeABAgAGQgJAEgQgBIgkAAIgGgBIAAgBIgQAAIgjgBIAAAAIgTAAIgWAAIghADIAAgDQALgDAQgBIgIgDQACgCAFAAIAKAAIBEABIg2gEIgFAAIAAgDIAJgDIgNgCIgVgDQABgCAFAAIARgBIAAAAQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAQAEACAFAAIAaABQAEgCAGAAQAcgEAzAEIB8AIQAZACAKAHQhtgKhtgDIAEAAIBPAEIAaABQANACAZAFIAPACIADAAIAAAAQALABAJgBQAEAIgGAGIgBAAIheAFQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAQAAAAAAABQAsgBAtgCIAAABQgTAIgWAFIgbAAIAAABIgBAAIAAACIANABIgeAFQgeAFg7ADIA2ACIgRABQgFAAABADQAZAEAPABIArABIAGgBIADACIAGAHQADAEAEACIAIADQAEACgBAEICfADQABADgDADQgEADgFABIh5AUIgKgBIAEAAQAGgCgCgCIg4gBQgTgBgPABIgYgBQgHAAAAAEIALABIgBAAIAAAEIAagCIA8AEIhHAMIgDgBQgqgFgcgBIg6AAIgEABQAAAAAAAAQgBABAAAAQAAAAAAABQAAAAABAAQA5ABA8AGQgZAEgLgBIgVgBIgXABIgiABIgOAAgAjGhCQAKADAHADIA6gBIgRgCQgMgCgMAAIglgCIADABgAC5AVQgEgFAGgGQADgDAIgBQBAgLBBgBQAkAAAOAKQAHAGAAAGQgBAIgJADQgEACgLAAgADOAJIgEACQgGADgHABIAoAAIAFgGIgXAAgADdAEQgBAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAICaAHQABAAAAAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQgKgFgXAAIh7gBIgDABg");
	this.shape_8.setTransform(339.875,385.9313);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#236BC0").s().p("AlzJAQgigFg/gRQhBgSghgFQhAgKhFAGIgaABQgPAAgKgGQgMgGgRgVQgfgpgNgYQgVgmgDgjQgDgtAbg8QAdhDBUiDQBRh9AdhJIATgyIANgdQgMgGgLgIQgYgTgIgbQgIgWAEgsIABgHIATABQAeABATgCIAXgBIAUABQAMABAZgEIAAAAIAUACQAAgBABAAQAAgBAAAAQAAgBgBAAQAAgBgBAAIgBgBIBHgMIAvACQgGgEgPgCIB7gUQAFgBADgDQAEgDgCgDIiggDQACgEgFgCIgIgDQgDgCgEgEIgFgHIgDgCIAAgBQABAAAAAAQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBgBAAQAJABAGgHQgHgCgPADQgIACgQAAIgnAAIg2gCQA6gDAfgFIAegFIARABIAEgBQAAAAABgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIgIgBQAXgFASgIIABgBQAwgCAxgEQABAAABAAQAAAAABAAQAAAAABgBQAAAAABAAQABgBAAAAQAAAAABgBQAAAAAAgBQAAAAgBgBIhcAEIAAAAQAGgGgEgIQgIABgLgBIgBAAIgDAAIgPgCQgZgFgMgCIgbgBIhPgEIgEAAQBuADBtAKQgKgHgagCIh8gIQgygEgcAEQgGABgEABIgbgBQgFAAgDgCQAPgUAkgVQAMgIALgBQAGgBAEABIAAgBIgdAAIAAgDIACAAIAAgBIAdAAQACgEAFgBQgCACgCADIOwABIAGgFQAEgFAEAAIABAEIgHAGIGWAAIAAADIgBABIlzgBIAGABQAPABAFAGQAGAIgHARIgeBJQgKAYgGAMQgLATgNAKQgUAQgpAHIgSADQgBALgDAJQgMAhgoAWQgNAIgWAJIgbALQgJAOgSAYQgSAZgDAUQgHAmAoA3IAdAqQAOAZABAWQACAZgOAaQgNAYgXASQgZAUgdAIIgKArQgIAfgCARQgEAiAJBOQAJBIgJAnQgHAkgWAeQgWAfgfATQgrAag/AGQgbADhZgBIhrACIgIAAQg5AAgpgHgAhUmvQgIABgEADQgGAGAFAFICtAIQAKAAAFgCQAJgDAAgIQAAgGgHgGQgOgLgkAAQhAABg/AMgADDmrQAFAGAPABIAZABIADgBQABAAAAgBQABAAAAgBQAAAAAAAAQAAgBgBAAIgigDQgIAAgDgDQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABgBAAgADZm5IhmAHIgDABIAAACQAUACAfgCIA0gDQAWABAHgIIgBgDQgNADgNAAgAC2ozQAAAAAAAAQAAABAAAAQgBAAABABQAAAAAAAAIBdAEIACAEQgRADgQAGQgBADAEAAQAXgBAVgMQgIgJgXAAIhKgBIgEABgAhemmQAIgBAGgDIADgCIAGAAIAWAAIgFAGgAppnRIACgKIBNACQgYAHgkABIgTAAgApknpIAWAAIASAAIABAAIAjABIgjAAIgBADIgqABIACgFgAoGnmIgCgBIAFABgAphnyIAEgLIAOACIgKADIAAADIAFAAIA3AEgAnhn4IgDgBIAlACQAMAAAMACIARACIg6ABQgHgDgKgDg");
	this.shape_9.setTransform(368.2097,429.7267);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},154).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7}]},2).to({state:[]},60).wait(112));

	// Capa_2
	this.instance_2 = new lib.Símbolo3("synched",0);
	this.instance_2.setTransform(204.9,388.65,1,1,0,0,0,76.2,33.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(217).to({_off:false},0).wait(1).to({regX:76.3,rotation:0.3466,x:205,y:388.45,startPosition:1},0).wait(1).to({rotation:0.6933,y:388.3,startPosition:2},0).wait(1).to({rotation:1.0399,y:388.2,startPosition:3},0).wait(1).to({rotation:1.3865,y:388.05,startPosition:4},0).wait(1).to({rotation:1.7331,x:204.95,y:387.9,startPosition:5},0).wait(1).to({rotation:1.4492,x:205.4,y:388.25,startPosition:6},0).wait(1).to({rotation:1.1653,x:205.85,y:388.55,startPosition:7},0).wait(1).to({rotation:0.8814,x:206.25,y:388.85,startPosition:8},0).wait(1).to({rotation:0.5975,x:206.65,y:389.2,startPosition:9},0).wait(1).to({rotation:0.3136,x:207.05,y:389.5,startPosition:10},0).wait(1).to({rotation:0.0297,x:207.55,y:389.85,startPosition:11},0).wait(1).to({rotation:-0.2542,x:207.95,y:390.15,startPosition:12},0).wait(1).to({rotation:-0.5381,x:208.35,y:390.5,startPosition:13},0).wait(1).to({rotation:-0.822,x:208.75,y:390.8,startPosition:14},0).wait(1).to({rotation:-1.1059,x:209.25,y:391.15,startPosition:15},0).wait(1).to({rotation:-1.3898,x:209.65,y:391.5,startPosition:16},0).wait(1).to({rotation:-1.6737,x:210,y:391.8,startPosition:17},0).wait(1).to({rotation:-1.9576,x:210.5,y:392.15,startPosition:18},0).wait(1).to({rotation:-2.2026,x:210.1,y:392.5,startPosition:19},0).wait(1).to({rotation:-2.4477,x:209.75,y:392.85,startPosition:20},0).wait(1).to({rotation:-2.6927,x:209.35,y:393.2,startPosition:0},0).wait(1).to({rotation:-2.9378,x:209,y:393.65,startPosition:1},0).wait(1).to({rotation:-3.1828,x:208.65,y:394,startPosition:2},0).wait(1).to({rotation:-3.4279,x:208.25,y:394.4,startPosition:3},0).wait(1).to({rotation:-3.6729,x:207.85,y:394.75,startPosition:4},0).wait(1).to({rotation:-3.918,x:207.45,y:395.1,startPosition:5},0).wait(1).to({rotation:-4.163,x:207.1,y:395.45,startPosition:6},0).wait(1).to({rotation:-4.4081,x:206.7,y:395.9,startPosition:7},0).wait(1).to({rotation:-4.1913,x:206.8,y:395.85,startPosition:8},0).wait(1).to({rotation:-3.9745,x:206.9,startPosition:9},0).wait(1).to({rotation:-3.7577,x:206.95,y:395.9,startPosition:10},0).wait(1).to({rotation:-3.5409,x:207.05,startPosition:11},0).wait(1).to({rotation:-3.3241,x:207.1,startPosition:12},0).wait(1).to({rotation:-3.1073,x:207.25,y:395.85,startPosition:13},0).wait(1).to({rotation:-2.8905,x:207.3,startPosition:14},0).wait(1).to({rotation:-2.6737,x:207.4,startPosition:15},0).wait(1).to({rotation:-2.4569,x:207.5,startPosition:16},0).wait(1).to({x:207.55,startPosition:17},0).wait(1).to({x:207.65,startPosition:18},0).wait(1).to({x:207.75,startPosition:19},0).wait(1).to({x:207.8,startPosition:20},0).wait(1).to({x:207.9,startPosition:0},0).wait(1).to({x:208,startPosition:1},0).wait(1).to({x:208.05,startPosition:2},0).wait(1).to({x:208.15,startPosition:3},0).wait(1).to({x:208.25,startPosition:4},0).wait(1).to({startPosition:5},0).wait(1).to({startPosition:6},0).wait(1).to({startPosition:7},0).wait(1).to({startPosition:8},0).wait(1).to({startPosition:9},0).wait(1).to({startPosition:10},0).wait(1).to({startPosition:11},0).wait(1).to({startPosition:12},0).wait(1).to({startPosition:13},0).wait(1).to({startPosition:14},0).wait(1).to({startPosition:15},0).to({_off:true},1).wait(54));

	// nina
	this.instance_3 = new lib.Interpolación2("synched",0);
	this.instance_3.setTransform(294.2,327.6,1,1,0,0,0,19.5,40.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#A39F94").s().p("AgLAsIgLgEIgBgGIgIgSIgEgKIgEgFIAAgBIgCgEIAAgCIgBgCIgCgIQgCgHABgDIADAAIgBgCQgDgHAAgEQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABAAQACAAABAEQACAIAFAKIABACIACABIACADIAEAFQADAAABACQABgFAJAAIAPABQAKAAAEABQAQAEAKARQACAGgBACQAAABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgMgJgNgHQgMgGgFAFIAEAaQAAAHgCAAQABAEgDADIgFABIgEAAg");
	this.shape_10.setTransform(297.8607,328.42);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#644459").s().p("AglBmQgngGgagSIgZgTQgQgMgcgQQgRgMgOgDIgSgEQgLgCgFgGQgHgGADgMQACgLAJgHQAGgGAMgFIAUgIIAXgNQAOgHAKgCIgKAIIAUgOQAFgEADAAIAEAAIAPgMQARgNAMAEQAAAEgIABQgGABgIAHIgMAMIgFAEQAIgGAGACIgOAMIAAABIADAAIABABQAFgBAFACIgPAQIADgBIAEgBIAMgKQAKgJAFAFQADADgHAFIgEAEQgBAAAAABQAAABAAAAQAAABAAAAQABABAAAAQAOgKASgBIAWgCQAJgDAOgKQABgBAAAAQABAAABAAQAAAAABAAQAAAAABABQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQgrAUgVAPIgDACIACAEQABADgCADIgBAEIAFgCQADgCACABQAFAAACAGIgBAKQADgCADADIAGAFQADAAAFgEQAMgJAYADQADAAACACQADAEgEAFQgEAEAAAEIALgCIACgCIAEgBIABABIATgFIAmgOQALgEAKgCIAOgEQANgEANgIQANgGAFABIAGAAQADABADgBIABgBIAAgFQAAgFABgCIAFgCIAGgEQAEgBACAHIACAJQgBgEAEgDIAIgCQgBgFAEgCIAHgCIAAgCQgDgDABgEIABgBQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAIAAgBIgDgHQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAIADABIAOAVIAEAGIAEAJIAIASIABAHIAAACIACAIIABADIABAHQADAagaAZQgRATgZAOIgGAFQgGAFgKACIgPAFQgJADgFAAIgBAAQgmAJg3ACIgNAAQggAAgYgEgAB1BYIAFgBIgCgBIgDACgACrATIAAABIABgCgACtARIAAAAIAAAAIAAAAgAhmgmIAGAAQAHAAgBAGIADgBQAMgMAMgIQgVAFgSAKgAhrgxIABABIAAADIADgCIAEgCQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBAAAAIgBgBIgJAFgAh3g4IAAABQgBAEgDABIAAABIAJgJIgFACg");
	this.shape_11.setTransform(271.7455,335.4876);

	this.instance_4 = new lib.Símbolo2("synched",0);
	this.instance_4.setTransform(297.45,329.75,1,1,0,0,0,50.9,92.3);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.instance_3}]},104).to({state:[{t:this.instance_4}]},11).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[]},1).wait(137));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(115).to({_off:false},0).wait(1).to({regX:17.3,regY:61.1,rotation:1.6666,x:264.85,y:297.55,startPosition:1},0).wait(1).to({rotation:3.3332,x:265.95,y:296.6,startPosition:2},0).wait(1).to({rotation:4.9999,x:267.1,y:295.7,startPosition:3},0).wait(1).to({rotation:6.6665,x:268.2,y:294.85,startPosition:4},0).wait(1).to({rotation:8.3331,x:269.3,y:293.95,startPosition:5},0).wait(1).to({rotation:9.9997,x:270.55,y:293.15,startPosition:6},0).wait(1).to({rotation:11.6664,x:271.7,y:292.4,startPosition:7},0).wait(1).to({rotation:13.333,x:272.95,y:291.6,startPosition:8},0).wait(1).to({rotation:14.9996,x:274.15,y:290.9,startPosition:9},0).wait(1).to({rotation:16.6662,x:275.45,y:290.2,startPosition:10},0).wait(1).to({rotation:18.3328,x:276.7,y:289.55,startPosition:11},0).wait(1).to({rotation:19.9995,x:278,y:288.9,startPosition:12},0).wait(1).to({rotation:21.6661,x:279.35,y:288.35,startPosition:13},0).wait(1).to({rotation:23.3327,x:280.7,y:287.75,startPosition:14},0).wait(1).to({rotation:24.9993,x:282.1,y:287.25,startPosition:15},0).wait(1).to({rotation:26.666,x:283.4,y:286.75,startPosition:16},0).wait(1).to({rotation:28.3326,x:284.8,y:286.35,startPosition:17},0).wait(1).to({rotation:29.9992,x:286.2,y:285.9,startPosition:18},0).wait(1).to({rotation:34.0905,x:289.9,y:285,startPosition:19},0).wait(1).to({rotation:38.1817,x:293.7,y:284.3,startPosition:20},0).wait(1).to({rotation:42.273,x:297.5,y:283.85,startPosition:21},0).wait(1).to({rotation:46.3642,x:301.35,y:283.6,startPosition:22},0).wait(1).to({rotation:50.4555,x:305.2,y:283.65,startPosition:23},0).wait(1).to({rotation:54.5467,x:309.05,y:283.85,startPosition:24},0).wait(1).to({rotation:58.638,x:312.8,y:284.3,startPosition:25},0).wait(1).to({rotation:62.7292,x:316.6,y:285.05,startPosition:26},0).wait(1).to({rotation:66.8205,x:320.25,y:285.95,startPosition:27},0).wait(1).to({rotation:70.9117,x:323.8,y:287.1,startPosition:28},0).wait(1).to({rotation:75.003,x:327.4,y:288.45,startPosition:29},0).wait(1).to({rotation:79.0942,x:330.75,y:290.05,startPosition:30},0).wait(1).to({rotation:83.1855,x:334.05,y:291.8,startPosition:31},0).wait(1).to({rotation:87.2767,x:337.15,y:293.75,startPosition:32},0).wait(1).to({rotation:91.368,x:340.15,y:295.9,startPosition:33},0).wait(1).to({rotation:97.216,x:344.4,y:299.3,startPosition:34},0).wait(1).to({rotation:103.064,x:348.2,y:303.05,startPosition:35},0).wait(1).to({rotation:108.912,x:351.6,y:307.05,startPosition:36},0).wait(1).to({rotation:114.76,x:354.55,y:311.25,startPosition:37},0).wait(1).to({rotation:120.608,x:357.15,y:315.7,startPosition:38},0).wait(1).to({rotation:126.456,x:359.2,y:320.25,startPosition:39},0).wait(1).to({rotation:132.304,x:360.85,y:324.9,startPosition:40},0).wait(1).to({rotation:138.152,x:362,y:329.55,startPosition:41},0).wait(1).to({rotation:144,x:362.7,y:334.2,startPosition:42},0).wait(1).to({rotation:149.848,x:362.9,y:338.8,startPosition:43},0).wait(1).to({rotation:155.696,x:362.65,y:343.3,startPosition:44},0).wait(1).to({rotation:161.544,x:361.95,y:347.7,startPosition:45},0).wait(1).to({rotation:167.392,x:360.75,y:351.85,startPosition:46},0).wait(1).to({rotation:167.669,x:360.65,y:355.25,startPosition:47},0).wait(1).to({rotation:167.946,x:360.6,y:358.65,startPosition:48},0).wait(1).to({rotation:168.223,x:360.45,y:362.1,startPosition:49},0).wait(1).to({rotation:168.5,x:360.3,y:365.5,startPosition:50},0).wait(1).to({rotation:168.777,x:360.2,y:368.85,startPosition:51},0).wait(1).to({rotation:169.054,x:360.1,y:372.3,startPosition:52},0).wait(1).to({rotation:169.331,x:360,y:375.7,startPosition:53},0).wait(1).to({rotation:169.608,x:359.9,y:379.1,startPosition:54},0).wait(1).to({rotation:169.885,x:359.7,y:382.55,startPosition:55},0).wait(1).to({rotation:170.5222,x:359.5,y:387.25,startPosition:56},0).wait(1).to({rotation:171.1594,x:359.15,y:391.95,startPosition:57},0).wait(1).to({rotation:171.7967,x:358.9,y:396.65,startPosition:58},0).wait(1).to({rotation:172.4339,x:358.6,y:401.4,startPosition:59},0).wait(1).to({rotation:173.0711,x:358.35,y:406.05,startPosition:60},0).wait(1).to({rotation:173.7083,x:358,y:410.7,startPosition:61},0).wait(1).to({rotation:174.3456,x:357.7,y:415.4,startPosition:62},0).wait(1).to({rotation:174.9828,x:357.35,y:420.1,startPosition:63},0).wait(1).to({rotation:175.62,x:357.1,y:424.75,startPosition:64},0).wait(1).to({x:356.4,y:426.4,startPosition:65},0).wait(1).to({x:355.7,y:428.05,startPosition:66},0).wait(1).to({x:355.05,y:429.7,startPosition:67},0).wait(1).to({x:354.35,y:431.3,startPosition:68},0).wait(1).to({x:353.65,y:432.95,startPosition:69},0).wait(1).to({x:353,y:434.6,startPosition:70},0).wait(1).to({x:352.3,y:436.2,startPosition:71},0).wait(1).to({x:351.6,y:437.85,startPosition:72},0).wait(1).to({x:350.95,y:439.5,startPosition:73},0).wait(1).to({x:350.25,y:441.15,startPosition:74},0).wait(1).to({x:349.6,y:442.75,startPosition:75},0).wait(1).to({startPosition:76},0).to({_off:true},1).wait(137));

	// Capa_3
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#345E4B").s().p("EgyFAD7QgHgFADgPQAEgOAGgKIAHgPQABgEAAgFIgCgJQgBgTAPgNQAIgGAGAAQALABAHAUQAXgPAaAFQAHABAEACQAHAGACAJQADASgLALQgHAHgQABIgaABQgPABgIAGQgGAFgGAKIgJARQgGAHgFADQgEACgDAAQgEAAgEgDgEAuvACpQgVgBgbgbQgOgNgCgIQgDgGACgHQABgHAGgDQALgIAQALIALAJQAHAGAFACIAKADIAKAEQALAGABAPQABARgNAGQgEABgFAAIgDAAgEAxfABUQgIgEgNgJIgVgNQghgSgmAIQgSAEgEgBQgKAAgIgHQgJgIABgKQABgPARgGQAKgDAUAAIBsACQATAAAMADQANADAKAJQALAJAEANQAEANgEANQgFAOgMAGQgJAFgKAAQgNAAgPgIgEAplAA/QgjgPgagQQgKgHgCgDQgGgJAFgJQAEgIAKgBQABAAAAAAQABAAAAAAQABgBAAAAQAAAAAAgBQAUgCAQAKQAEACANACQAMABAEAEQAEAEAEALIAMAOQAHAIgCAIQgCALgOABIgBAAQgIAAgMgEgEgt5AAYQgBgHAIgJQAIgKABgFQABgEgBgJQgCgJACgFQACgEAHgDIALgGIALgIIALgIIACgBQAIgFAJgDQAEgBACgCIASADIAEABIAIgDQAGgBAGADQAHACACAGQAEAIgFAKQgGAJgJAEIABAGQAAAIgJAEQgGADgKAAIggAAIgNAKIgcAWQgJAGgGAAQgEAAgCgCgEgwrAAIQgMgCgDgIQgCgFABgJQACgQAEgEQAHgGADgEIACgKQACgKAHgJIABAAQAIgIALgDQASgCAJACQAQAEAEAMQADAGgCAOQgCAPgFAHIgDADQgEAEgKADQgMACgDACQgFACgGAGIgKAIQgIAGgJAAIgCAAgEgyWgA0IgHgUQgFgNAEgIQABgDAIgHQAUgOAFgIQAFgKAEAAQAGgBAEAKQAIATgGAJIgIAHQgLAJgGAMIgIAOQgFAFgFAAIgEgBgAf6h4IgNgEQgngLgPgQIgOgVQgIgMgIgFIgJgFQgFgDgCgEQgCgEACgGQABgFAFgDIAFgDQAGgDAJAAQAOABAWAIIATAJQAqAUASAXQAKALABAKQACAPgKAHQgFAEgIAAQgIAAgKgDgEAq1gCkIgJgNQgFgHgOgMIgMgKIgGgIQgIgOAFgLQADgGAGgDQAHgDAGADQgBgDAFgBQAggDAcAPQARAJABALQABAFgCAIIAAABIgDANIAAANQAAAIgDAEQgFAJgUAAQgRAAgGgFg");
	this.shape_12.setTransform(325.5926,252.8834);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#3A614E").s().p("AAGBHQgFgBgDgCQAEgHACgPQACgOgDgGQgDgMgQgEQgJgCgSACQgLADgIAIIgBAAQACgGAGgHQgBgWALgeQAEgMAEgFQAIgIANgBQASAAAMAQIAFAHIAGABQALABAFAEQAJAGgCAIQgCAHgJAEIgJADQABAFACACQACACAKAEQAMACAGAJQAGAMgGAJQgEAHgOAIQgFAFgJAMQgHAHgLAAIgFAAg");
	this.shape_13.setTransform(21.494,243.169);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#3C6350").s().p("Eg0XAHCQgMgCgHgIQgLgMABghQAAgqgKhSQgSiZgQhjQgIgvADgZQAFgiAYgiQASgaAhgeQA6g0AsgNQAcgJBAAAIDSADQAkAAARACQAdAEAVAKIAjAWQAPAJAMAFIABgCIAEgBIAygCIADgCQgFgDACgEQABgCADgBIAUgHQAMgPACgUQABgKAEgCQADgCAIACICNAlQAPgEAPgDQAZgDA7AAIDHADQAAAHgNAAIgdABIARACIgNAPQAPgCAPAGQAOAGAJALQicgaiUAzQg1AUgbAHQgQAEgOACIgjAWIkhC3IgaASIAEACQgcARgbATIgQAOIg2AxQgiAfgVAWQgcAfgaAkQgMASgHASIgEgFIgsBDQgCgHgJAAQgFAAgGACIgKAOQgSAWgPAGQgJAEgKAAIgEAAgEgyUAFFIgDAEIgDAHQgCAEgCABQAGABADgCIABgCQgBgJAKgOIAAgBIgJALgEgx4AEfIgCAEIAKgMgEgxpABUQgPANACATIABAJQABAFgBAEIgHAPQgHAKgDAOQgDAPAHAFQAGAFAIgEQAGgDAFgHIAKgRQAFgKAGgFQAJgGAPgBIAagBQAPgBAIgHQALgLgEgSQgBgJgHgGQgFgCgGgBQgagFgYAPQgGgUgMgBIgBAAQgFAAgIAGgEgspgCCQgJAEgIAFIgCAAIgLAIIgMAIIgLAGQgGADgCAEQgCAFABAJQACAJgBAEQgBAFgJALQgHAJABAHQAGAGAPgKIAcgXIANgKIAfAAQAKAAAGgDQAKgEAAgIIgCgGQAKgEAFgJQAGgKgEgIQgDgGgGgCQgGgDgHABIgIADIgEgBIgSgDQgCACgDABgEgwDgDYQgFAFgEAMQgKAeABAXQgGAHgCAGQgIAJgCAKIgCAKQgCAEgIAGQgEAEgCAQQgBAJACAFQADAJAMACQALABAIgHIALgJQAGgGAEgCQAEgCAMgCQAJgDAFgEIACgDQAFACAFABQAOACAJgJQAIgMAGgFQAOgIAEgHQAGgJgHgMQgGgJgLgDQgLgEgCgCQgCgCgBgFIAKgDQAJgEABgHQADgIgJgGQgFgEgLgBIgGgBIgFgHQgNgQgTAAQgMABgIAIgEgxwgDBQgEAAgGAKQgEAIgUAOQgIAHgCADQgDAIAEANIAHAUQAIADAGgHIAIgOQAHgMAKgJIAJgHQAFgJgHgTQgFgJgFAAIAAAAgEgmygDaIACAAIAVgIQgZACgMACIgBABIANADIABAAIABAAgEglPgDjQgYACgaAGIBLgHIAYgCgEAwRADYQiBg+hBgbQhCgaiBgjQjgg9hxgbQi7gwiYgeQhygXgegHIgTgEIgZAOQgOAIgMACQgGACgTAAIgYgCQgVgCgTgLIgEAAQgagEgRgKQgKgFgCgGIgBgCIgMgCQgLgDgSgGIgdgLQgWgHgvgBIiMgCQABgFgJgBQg5gEg7gQQgjgJgMAAIgOgBQgJgBgDgFQASgIAcACQANABAdAFQAbAGAPAAIAbgBIAbAAIAjAFQATACAcAAIC8ADQACgSALgPQARgXAcgPQAagNAfgDQAagEAhADQARABAqAGIBGAKIgFADQgEADgCAFQgBAGACAEQACAEAFADIAIAFQAIAFAJAMIAOAVQAOAQAnALIAOAEQAVAGAJgHQALgHgDgPQgBgKgKgLQgSgXgpgUIgTgJICBARIBrAMQA8AGAvABQBHABBcgHICjgRIApgDIAMAKQANAMAFAHIAKANQAGAFAQAAQAUAAAGgJQACgEAAgIIAAgNIADgNIADAAQATADA7AMQAvALAeAAIA2gBQAhgCAVAFQAXAFAhASIgCgGIgEgIQgBgGACgDIAHgIIABgKQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQABAGAEADQAHgDAIADQABAMAKAGIAEgcQADgBADAEQACADAAAFIAABBQAYAMAOAEQANAEAhAFQAdAFAPAGQApAQAdAuQAVAiASA3QAXBHgBAtQgBAggLAbQgMAdgWASQgjAcg8AEIgQAAQhRAAhogrgEAt3AAnQgFADgCAHQgBAHACAGQADAIANANQAcAbAVABQAGABAGgCQANgGgBgRQgCgPgKgGIgKgEIgKgDQgGgCgGgGIgMgJQgJgGgIAAQgFAAgFADgEAw4AAAIAVANQANAJAIAEQAbAOAUgLQAMgGAEgOQAFgMgEgNQgEgNgLgJQgKgJgOgDQgMgDgTAAIhsgCQgUAAgJADQgRAGgCAPQAAAKAIAIQAIAHALAAQAEABARgEQAMgDALAAQAZAAAYAMgEAovgBBQAAABgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgLABgEAJQgFAJAGAJQADADAJAHQAaAQAjAOQAOAFAIgBQANgBADgKQACgIgIgIIgLgOQgEgLgEgEQgFgEgLgBQgNgCgFgCQgMgJgQAAIgHAAgAbmh2IABACIATgBIgDgBIgDAAgAcGh6IgBAAIACACIADgBIgDgBIgBAAgAaaiQIABgCIgBgBIgEAAIgCgBIAGAEgEAxHgDHIAJAGIAAgLQAAgZgLgGQACASAAASgA7dieQgGgEgIgJIgNgOIgMgJQgHgFgDgEQgFgGAAgIQABgIAGgEQAGAGAJgDQgEgGAHgFQAFgFAJgCQA3gLBDAIQA0AGBEATQAWAHANABQAUACANgIQADADABAEQABAEgDAEIADABQAWgCAWgBQAdAAAJgBIAngKQAYgGAPACQgOAMgSAFQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQgBACgEABQgQAEgSACQgNACgCAGIgwADQgDAIgQACIiQANIg+AFQgjACgcAAIgFAAQgXAAgLgHgA3ejFIAAACIACABIgCgDIACgBIgCAAIAAABgA5ejZQAoAGAmgEQgggNghgDQgLgCgCgFIhwAAQgWAAgGAKIADAEIBJAJQASACAIgCIATgEIACAAQAIAAAJACgADpiiQgegBgTgIIgIgEIgOgHQgNgHgKgBQgCgEACgEIgHgDQgRgDgHgEQgLgLgIgBQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAQACAOAEQAEgBAFABIAKAEIAJgEQAHgEAEABQgJgFgUgFIgmgMQgXgHgQAAIAAgCIACgBQAQgDAVAGIAjANQAmAOBFAHIAUADIAPAGQAQAEAcgHQAggIANAAQAAAGgFAHQAPgHAJgCIAZgCICWgGIipgDQgCgDAGAAQCFgBBBAEQAJABABAEQgVAGglABIiKAHQgSABgJACQgHABgSAIIgiAPQgVAJgLADQgRAFgZAAIgKAAgADYjNIAjgBQgkgGghgBQAMAIAWAAgAChjSIAJADIAHABIAAAAQAEABACgBIgKgFIgCgBIgCgBIgMAAQABACADABgAFLjOIAUAAIgPgCIgCAAgAsxjEQgVgDgHgJQALADANgBIgOgFQASgDASABIAZAEQAPACAKAAQAMgBAkgJQA3gMAzAIQAJABAAAFQAAADgFADQguAahCAAQgpAAhJgNgAsQjEIAQAAIgXgCQADACAEAAgAq6jTQA0ACA1gIIg4AAQgiAAgPAGgEgn7gETQgGgJgBgVQgEgwgIguIgMA7QgGAAADgIIAJgvQADgJAAgHIgEgTQgCgMACgHQAEgCADAIIAGAgIAKBEQADAQAAAOIgBAQQAAAKADAGIABAEQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgBAAg");
	this.shape_14.setTransform(325.3362,258.663);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},217).to({state:[]},58).wait(54));

	// fondo
	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("EgzKAmwMAAAhNfMBmVAAAMAAABNfg");
	this.shape_15.setTransform(323.525,242.025);

	this.instance_5 = new lib.CachedBmp_4();
	this.instance_5.setTransform(87,87.7,0.5,0.5);

	this.instance_6 = new lib.CachedBmp_5();
	this.instance_6.setTransform(-3.95,-5.95,0.5,0.5);

	this.instance_7 = new lib.CachedBmp_6();
	this.instance_7.setTransform(87,87.7,0.5,0.5);

	this.instance_8 = new lib.Interpolación3("synched",0);
	this.instance_8.setTransform(527.25,241.1);
	this.instance_8._off = true;

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#3C6350").s().p("ANdLfQAAgIAOgLQAfgaARgfQAUgkgDgjQg2BHg2A8QgFAGgEABQgCABgDgCQgDgBgBgDQgIAIgEANIgCgXQgFAFgGgFQgDgDgBgHQgDgSAOgLQgCAAgBgEIBdhBQAkgZAXgDQAFAngWAoQgUAjgjAcQgHAGAAAEQAAAGALAFQALAFAAAFQgbgFAAgQgANYKoIgMAOIgNANQgHAHgDAGIACAAQADgFAHgFIALgJQAEgDAEgHIAIgKIAMgMQAGgIADgGIgZAZgANHKrIgVAbQADAAAEgEIATgaIgBAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAgBABgAM7KYIgGAEIgIAFIgIAFIgHAIIgGAFQgCADABAGIAAAKQAFgBACgGQABgFgCgEQARgTAUgNIgBAAQgDAAgDACgANWKiQADAAAEgEIATgTQAUgVADgFIgBgBQgYAWgYAcgAutkFQgHgLAGgPQAFgNAMgNQAZgZAmgcQDOidD7hGIAngLQAXgHAPgHQAxgWAhgqIACgDIAAgEQAAgGAIgFIADgCQALgWgBgTQgBgFACgEQACgFADACQAJAUgJAYIALgEIAAgDIAUADQABAEgFADIgIADQgGABgDADIgCACQgCACgFABIgKAEIgJAOQgnA2g+AZQgTAIgcAHIgxANQgkAJg5AXQj9BkiQCNQgRAQAHAMIAEAHQACAEgDABgAtyl9QATgcAbgZQAXgUAdgSIAlgVIAngTIBCgjQAUgJAwgRQBCgWAbgHIA2gLIA2gMQA0gOA3gbQgGAPgXALQglAThBANQhbATgPAEIhNAaIgjALQgVAGgNAHIgbAPIgaAQIghAPQgVAKgMAHQgPAJgdAWIgPAKQgJAGgFAFQgNAMgPAeg");
	this.shape_16.setTransform(92.7299,308.4077);

	this.instance_9 = new lib.CachedBmp_8();
	this.instance_9.setTransform(90.95,93.65,0.5,0.5);

	this.instance_10 = new lib.CachedBmp_9();
	this.instance_10.setTransform(-7,-7.95,0.5,0.5);

	this.instance_11 = new lib.CachedBmp_10();
	this.instance_11.setTransform(90.95,93.65,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15}]}).to({state:[{t:this.instance_6},{t:this.instance_5}]},12).to({state:[{t:this.instance_6},{t:this.instance_7}]},34).to({state:[{t:this.instance_8}]},58).to({state:[{t:this.instance_8}]},54).to({state:[{t:this.shape_16},{t:this.instance_8}]},59).to({state:[{t:this.shape_16},{t:this.instance_8}]},3).to({state:[{t:this.instance_10},{t:this.instance_9}]},55).to({state:[{t:this.instance_10},{t:this.instance_11}]},22).wait(32));
	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(104).to({_off:false},0).to({x:124.25,y:242.1},54).wait(59).to({regX:2.8,regY:2.6,scaleX:1.2609,scaleY:1.2605,x:469.55,y:183.5},0).wait(3).to({startPosition:0},0).to({_off:true},55).wait(54));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-94.6,113.9,1240.1999999999998,392.70000000000005);
// library properties:
lib.properties = {
	id: '5751811986003F4E9C6D93081356792D',
	width: 640,
	height: 480,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/CachedBmp_17.png", id:"CachedBmp_17"},
		{src:"images/cuento_macabro_atlas_1.png", id:"cuento_macabro_atlas_1"},
		{src:"images/cuento_macabro_atlas_2.png", id:"cuento_macabro_atlas_2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['5751811986003F4E9C6D93081356792D'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;